// Code generated by go-swagger; DO NOT EDIT.

package permissions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRemoveProjectUserPermissionParams creates a new RemoveProjectUserPermissionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRemoveProjectUserPermissionParams() *RemoveProjectUserPermissionParams {
	return &RemoveProjectUserPermissionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRemoveProjectUserPermissionParamsWithTimeout creates a new RemoveProjectUserPermissionParams object
// with the ability to set a timeout on a request.
func NewRemoveProjectUserPermissionParamsWithTimeout(timeout time.Duration) *RemoveProjectUserPermissionParams {
	return &RemoveProjectUserPermissionParams{
		timeout: timeout,
	}
}

// NewRemoveProjectUserPermissionParamsWithContext creates a new RemoveProjectUserPermissionParams object
// with the ability to set a context for a request.
func NewRemoveProjectUserPermissionParamsWithContext(ctx context.Context) *RemoveProjectUserPermissionParams {
	return &RemoveProjectUserPermissionParams{
		Context: ctx,
	}
}

// NewRemoveProjectUserPermissionParamsWithHTTPClient creates a new RemoveProjectUserPermissionParams object
// with the ability to set a custom HTTPClient for a request.
func NewRemoveProjectUserPermissionParamsWithHTTPClient(client *http.Client) *RemoveProjectUserPermissionParams {
	return &RemoveProjectUserPermissionParams{
		HTTPClient: client,
	}
}

/*
RemoveProjectUserPermissionParams contains all the parameters to send to the API endpoint

	for the remove project user permission operation.

	Typically these are written to a http.Request.
*/
type RemoveProjectUserPermissionParams struct {

	// Body.
	Body RemoveProjectUserPermissionBody

	// ProjectID.
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the remove project user permission params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RemoveProjectUserPermissionParams) WithDefaults() *RemoveProjectUserPermissionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the remove project user permission params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RemoveProjectUserPermissionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the remove project user permission params
func (o *RemoveProjectUserPermissionParams) WithTimeout(timeout time.Duration) *RemoveProjectUserPermissionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the remove project user permission params
func (o *RemoveProjectUserPermissionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the remove project user permission params
func (o *RemoveProjectUserPermissionParams) WithContext(ctx context.Context) *RemoveProjectUserPermissionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the remove project user permission params
func (o *RemoveProjectUserPermissionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the remove project user permission params
func (o *RemoveProjectUserPermissionParams) WithHTTPClient(client *http.Client) *RemoveProjectUserPermissionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the remove project user permission params
func (o *RemoveProjectUserPermissionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the remove project user permission params
func (o *RemoveProjectUserPermissionParams) WithBody(body RemoveProjectUserPermissionBody) *RemoveProjectUserPermissionParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the remove project user permission params
func (o *RemoveProjectUserPermissionParams) SetBody(body RemoveProjectUserPermissionBody) {
	o.Body = body
}

// WithProjectID adds the projectID to the remove project user permission params
func (o *RemoveProjectUserPermissionParams) WithProjectID(projectID string) *RemoveProjectUserPermissionParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the remove project user permission params
func (o *RemoveProjectUserPermissionParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *RemoveProjectUserPermissionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param projectId
	if err := r.SetPathParam("projectId", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
