// Code generated by go-swagger; DO NOT EDIT.

package object_storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/CudoVentures/terraform-provider-cudo/internal/models"
)

// DeleteObjectStorageKeyReader is a Reader for the DeleteObjectStorageKey structure.
type DeleteObjectStorageKeyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteObjectStorageKeyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteObjectStorageKeyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDeleteObjectStorageKeyDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteObjectStorageKeyOK creates a DeleteObjectStorageKeyOK with default headers values
func NewDeleteObjectStorageKeyOK() *DeleteObjectStorageKeyOK {
	return &DeleteObjectStorageKeyOK{}
}

/*
DeleteObjectStorageKeyOK describes a response with status code 200, with default header values.

A successful response.
*/
type DeleteObjectStorageKeyOK struct {
	Payload models.DeleteObjectStorageKeyResponse
}

// IsSuccess returns true when this delete object storage key o k response has a 2xx status code
func (o *DeleteObjectStorageKeyOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete object storage key o k response has a 3xx status code
func (o *DeleteObjectStorageKeyOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete object storage key o k response has a 4xx status code
func (o *DeleteObjectStorageKeyOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete object storage key o k response has a 5xx status code
func (o *DeleteObjectStorageKeyOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete object storage key o k response a status code equal to that given
func (o *DeleteObjectStorageKeyOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete object storage key o k response
func (o *DeleteObjectStorageKeyOK) Code() int {
	return 200
}

func (o *DeleteObjectStorageKeyOK) Error() string {
	return fmt.Sprintf("[POST /v1/projects/{projectId}/object-storage/users/{id}/keys][%d] deleteObjectStorageKeyOK  %+v", 200, o.Payload)
}

func (o *DeleteObjectStorageKeyOK) String() string {
	return fmt.Sprintf("[POST /v1/projects/{projectId}/object-storage/users/{id}/keys][%d] deleteObjectStorageKeyOK  %+v", 200, o.Payload)
}

func (o *DeleteObjectStorageKeyOK) GetPayload() models.DeleteObjectStorageKeyResponse {
	return o.Payload
}

func (o *DeleteObjectStorageKeyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteObjectStorageKeyDefault creates a DeleteObjectStorageKeyDefault with default headers values
func NewDeleteObjectStorageKeyDefault(code int) *DeleteObjectStorageKeyDefault {
	return &DeleteObjectStorageKeyDefault{
		_statusCode: code,
	}
}

/*
DeleteObjectStorageKeyDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type DeleteObjectStorageKeyDefault struct {
	_statusCode int

	Payload *models.Status
}

// IsSuccess returns true when this delete object storage key default response has a 2xx status code
func (o *DeleteObjectStorageKeyDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this delete object storage key default response has a 3xx status code
func (o *DeleteObjectStorageKeyDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this delete object storage key default response has a 4xx status code
func (o *DeleteObjectStorageKeyDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this delete object storage key default response has a 5xx status code
func (o *DeleteObjectStorageKeyDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this delete object storage key default response a status code equal to that given
func (o *DeleteObjectStorageKeyDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the delete object storage key default response
func (o *DeleteObjectStorageKeyDefault) Code() int {
	return o._statusCode
}

func (o *DeleteObjectStorageKeyDefault) Error() string {
	return fmt.Sprintf("[POST /v1/projects/{projectId}/object-storage/users/{id}/keys][%d] DeleteObjectStorageKey default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteObjectStorageKeyDefault) String() string {
	return fmt.Sprintf("[POST /v1/projects/{projectId}/object-storage/users/{id}/keys][%d] DeleteObjectStorageKey default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteObjectStorageKeyDefault) GetPayload() *models.Status {
	return o.Payload
}

func (o *DeleteObjectStorageKeyDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
