// Code generated by go-swagger; DO NOT EDIT.

package object_storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/CudoVentures/terraform-provider-cudo/internal/models"
)

// GetObjectStorageSessionKeyReader is a Reader for the GetObjectStorageSessionKey structure.
type GetObjectStorageSessionKeyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetObjectStorageSessionKeyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetObjectStorageSessionKeyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetObjectStorageSessionKeyDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetObjectStorageSessionKeyOK creates a GetObjectStorageSessionKeyOK with default headers values
func NewGetObjectStorageSessionKeyOK() *GetObjectStorageSessionKeyOK {
	return &GetObjectStorageSessionKeyOK{}
}

/*
GetObjectStorageSessionKeyOK describes a response with status code 200, with default header values.

A successful response.
*/
type GetObjectStorageSessionKeyOK struct {
	Payload *models.GetObjectStorageSessionKeyResponse
}

// IsSuccess returns true when this get object storage session key o k response has a 2xx status code
func (o *GetObjectStorageSessionKeyOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get object storage session key o k response has a 3xx status code
func (o *GetObjectStorageSessionKeyOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get object storage session key o k response has a 4xx status code
func (o *GetObjectStorageSessionKeyOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get object storage session key o k response has a 5xx status code
func (o *GetObjectStorageSessionKeyOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get object storage session key o k response a status code equal to that given
func (o *GetObjectStorageSessionKeyOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get object storage session key o k response
func (o *GetObjectStorageSessionKeyOK) Code() int {
	return 200
}

func (o *GetObjectStorageSessionKeyOK) Error() string {
	return fmt.Sprintf("[GET /v1/projects/{projectId}/object-storage/session-key][%d] getObjectStorageSessionKeyOK  %+v", 200, o.Payload)
}

func (o *GetObjectStorageSessionKeyOK) String() string {
	return fmt.Sprintf("[GET /v1/projects/{projectId}/object-storage/session-key][%d] getObjectStorageSessionKeyOK  %+v", 200, o.Payload)
}

func (o *GetObjectStorageSessionKeyOK) GetPayload() *models.GetObjectStorageSessionKeyResponse {
	return o.Payload
}

func (o *GetObjectStorageSessionKeyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetObjectStorageSessionKeyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetObjectStorageSessionKeyDefault creates a GetObjectStorageSessionKeyDefault with default headers values
func NewGetObjectStorageSessionKeyDefault(code int) *GetObjectStorageSessionKeyDefault {
	return &GetObjectStorageSessionKeyDefault{
		_statusCode: code,
	}
}

/*
GetObjectStorageSessionKeyDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type GetObjectStorageSessionKeyDefault struct {
	_statusCode int

	Payload *models.Status
}

// IsSuccess returns true when this get object storage session key default response has a 2xx status code
func (o *GetObjectStorageSessionKeyDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get object storage session key default response has a 3xx status code
func (o *GetObjectStorageSessionKeyDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get object storage session key default response has a 4xx status code
func (o *GetObjectStorageSessionKeyDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get object storage session key default response has a 5xx status code
func (o *GetObjectStorageSessionKeyDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get object storage session key default response a status code equal to that given
func (o *GetObjectStorageSessionKeyDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get object storage session key default response
func (o *GetObjectStorageSessionKeyDefault) Code() int {
	return o._statusCode
}

func (o *GetObjectStorageSessionKeyDefault) Error() string {
	return fmt.Sprintf("[GET /v1/projects/{projectId}/object-storage/session-key][%d] GetObjectStorageSessionKey default  %+v", o._statusCode, o.Payload)
}

func (o *GetObjectStorageSessionKeyDefault) String() string {
	return fmt.Sprintf("[GET /v1/projects/{projectId}/object-storage/session-key][%d] GetObjectStorageSessionKey default  %+v", o._statusCode, o.Payload)
}

func (o *GetObjectStorageSessionKeyDefault) GetPayload() *models.Status {
	return o.Payload
}

func (o *GetObjectStorageSessionKeyDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
