// Code generated by go-swagger; DO NOT EDIT.

package object_storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewListObjectStorageKeysParams creates a new ListObjectStorageKeysParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListObjectStorageKeysParams() *ListObjectStorageKeysParams {
	return &ListObjectStorageKeysParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListObjectStorageKeysParamsWithTimeout creates a new ListObjectStorageKeysParams object
// with the ability to set a timeout on a request.
func NewListObjectStorageKeysParamsWithTimeout(timeout time.Duration) *ListObjectStorageKeysParams {
	return &ListObjectStorageKeysParams{
		timeout: timeout,
	}
}

// NewListObjectStorageKeysParamsWithContext creates a new ListObjectStorageKeysParams object
// with the ability to set a context for a request.
func NewListObjectStorageKeysParamsWithContext(ctx context.Context) *ListObjectStorageKeysParams {
	return &ListObjectStorageKeysParams{
		Context: ctx,
	}
}

// NewListObjectStorageKeysParamsWithHTTPClient creates a new ListObjectStorageKeysParams object
// with the ability to set a custom HTTPClient for a request.
func NewListObjectStorageKeysParamsWithHTTPClient(client *http.Client) *ListObjectStorageKeysParams {
	return &ListObjectStorageKeysParams{
		HTTPClient: client,
	}
}

/*
ListObjectStorageKeysParams contains all the parameters to send to the API endpoint

	for the list object storage keys operation.

	Typically these are written to a http.Request.
*/
type ListObjectStorageKeysParams struct {

	// ID.
	ID string

	// PageNumber.
	//
	// Format: int32
	PageNumber *int32

	// PageSize.
	//
	// Format: int32
	PageSize *int32

	// ProjectID.
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list object storage keys params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListObjectStorageKeysParams) WithDefaults() *ListObjectStorageKeysParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list object storage keys params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListObjectStorageKeysParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list object storage keys params
func (o *ListObjectStorageKeysParams) WithTimeout(timeout time.Duration) *ListObjectStorageKeysParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list object storage keys params
func (o *ListObjectStorageKeysParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list object storage keys params
func (o *ListObjectStorageKeysParams) WithContext(ctx context.Context) *ListObjectStorageKeysParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list object storage keys params
func (o *ListObjectStorageKeysParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list object storage keys params
func (o *ListObjectStorageKeysParams) WithHTTPClient(client *http.Client) *ListObjectStorageKeysParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list object storage keys params
func (o *ListObjectStorageKeysParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the list object storage keys params
func (o *ListObjectStorageKeysParams) WithID(id string) *ListObjectStorageKeysParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the list object storage keys params
func (o *ListObjectStorageKeysParams) SetID(id string) {
	o.ID = id
}

// WithPageNumber adds the pageNumber to the list object storage keys params
func (o *ListObjectStorageKeysParams) WithPageNumber(pageNumber *int32) *ListObjectStorageKeysParams {
	o.SetPageNumber(pageNumber)
	return o
}

// SetPageNumber adds the pageNumber to the list object storage keys params
func (o *ListObjectStorageKeysParams) SetPageNumber(pageNumber *int32) {
	o.PageNumber = pageNumber
}

// WithPageSize adds the pageSize to the list object storage keys params
func (o *ListObjectStorageKeysParams) WithPageSize(pageSize *int32) *ListObjectStorageKeysParams {
	o.SetPageSize(pageSize)
	return o
}

// SetPageSize adds the pageSize to the list object storage keys params
func (o *ListObjectStorageKeysParams) SetPageSize(pageSize *int32) {
	o.PageSize = pageSize
}

// WithProjectID adds the projectID to the list object storage keys params
func (o *ListObjectStorageKeysParams) WithProjectID(projectID string) *ListObjectStorageKeysParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the list object storage keys params
func (o *ListObjectStorageKeysParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *ListObjectStorageKeysParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.PageNumber != nil {

		// query param pageNumber
		var qrPageNumber int32

		if o.PageNumber != nil {
			qrPageNumber = *o.PageNumber
		}
		qPageNumber := swag.FormatInt32(qrPageNumber)
		if qPageNumber != "" {

			if err := r.SetQueryParam("pageNumber", qPageNumber); err != nil {
				return err
			}
		}
	}

	if o.PageSize != nil {

		// query param pageSize
		var qrPageSize int32

		if o.PageSize != nil {
			qrPageSize = *o.PageSize
		}
		qPageSize := swag.FormatInt32(qrPageSize)
		if qPageSize != "" {

			if err := r.SetQueryParam("pageSize", qPageSize); err != nil {
				return err
			}
		}
	}

	// path param projectId
	if err := r.SetPathParam("projectId", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
