// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InstanceMonitoringItem instance monitoring item
//
// swagger:model InstanceMonitoringItem
type InstanceMonitoringItem struct {

	// cpu
	CPU float32 `json:"cpu,omitempty"`

	// disk rd bytes
	DiskRdBytes int32 `json:"diskRdBytes,omitempty"`

	// disk rd iops
	DiskRdIops int32 `json:"diskRdIops,omitempty"`

	// disk wr bytes
	DiskWrBytes int32 `json:"diskWrBytes,omitempty"`

	// disk wr iops
	DiskWrIops int32 `json:"diskWrIops,omitempty"`

	// memory
	Memory int32 `json:"memory,omitempty"`

	// net rx
	NetRx int32 `json:"netRx,omitempty"`

	// net tx
	NetTx int32 `json:"netTx,omitempty"`

	// timestamp
	Timestamp string `json:"timestamp,omitempty"`
}

// Validate validates this instance monitoring item
func (m *InstanceMonitoringItem) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this instance monitoring item based on context it is used
func (m *InstanceMonitoringItem) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InstanceMonitoringItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InstanceMonitoringItem) UnmarshalBinary(b []byte) error {
	var res InstanceMonitoringItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
