// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ListSecurityGroupsResponse list security groups response
//
// swagger:model ListSecurityGroupsResponse
type ListSecurityGroupsResponse struct {

	// page number
	// Required: true
	PageNumber *int32 `json:"pageNumber"`

	// page size
	// Required: true
	PageSize *int32 `json:"pageSize"`

	// security groups
	// Required: true
	SecurityGroups []*SecurityGroup `json:"securityGroups"`

	// total count
	// Required: true
	TotalCount *int32 `json:"totalCount"`
}

// Validate validates this list security groups response
func (m *ListSecurityGroupsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePageNumber(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePageSize(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSecurityGroups(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTotalCount(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ListSecurityGroupsResponse) validatePageNumber(formats strfmt.Registry) error {

	if err := validate.Required("pageNumber", "body", m.PageNumber); err != nil {
		return err
	}

	return nil
}

func (m *ListSecurityGroupsResponse) validatePageSize(formats strfmt.Registry) error {

	if err := validate.Required("pageSize", "body", m.PageSize); err != nil {
		return err
	}

	return nil
}

func (m *ListSecurityGroupsResponse) validateSecurityGroups(formats strfmt.Registry) error {

	if err := validate.Required("securityGroups", "body", m.SecurityGroups); err != nil {
		return err
	}

	for i := 0; i < len(m.SecurityGroups); i++ {
		if swag.IsZero(m.SecurityGroups[i]) { // not required
			continue
		}

		if m.SecurityGroups[i] != nil {
			if err := m.SecurityGroups[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("securityGroups" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("securityGroups" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ListSecurityGroupsResponse) validateTotalCount(formats strfmt.Registry) error {

	if err := validate.Required("totalCount", "body", m.TotalCount); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this list security groups response based on the context it is used
func (m *ListSecurityGroupsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSecurityGroups(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ListSecurityGroupsResponse) contextValidateSecurityGroups(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.SecurityGroups); i++ {

		if m.SecurityGroups[i] != nil {

			if swag.IsZero(m.SecurityGroups[i]) { // not required
				return nil
			}

			if err := m.SecurityGroups[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("securityGroups" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("securityGroups" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ListSecurityGroupsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ListSecurityGroupsResponse) UnmarshalBinary(b []byte) error {
	var res ListSecurityGroupsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
