// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// VMNIC VM n i c
//
// swagger:model VM.NIC
type VMNIC struct {

	// external Ip address
	ExternalIPAddress string `json:"externalIpAddress,omitempty"`

	// internal Ip address
	InternalIPAddress string `json:"internalIpAddress,omitempty"`

	// network address
	NetworkAddress string `json:"networkAddress,omitempty"`

	// network Id
	NetworkID string `json:"networkId,omitempty"`

	// security group ids
	SecurityGroupIds []string `json:"securityGroupIds"`
}

// Validate validates this VM n i c
func (m *VMNIC) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this VM n i c based on context it is used
func (m *VMNIC) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VMNIC) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VMNIC) UnmarshalBinary(b []byte) error {
	var res VMNIC
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
