// Code generated by go-swagger; DO NOT EDIT.

package disks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/CudoVentures/terraform-provider-cudo/internal/models"
)

// DeleteStorageDiskReader is a Reader for the DeleteStorageDisk structure.
type DeleteStorageDiskReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteStorageDiskReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteStorageDiskOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDeleteStorageDiskDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteStorageDiskOK creates a DeleteStorageDiskOK with default headers values
func NewDeleteStorageDiskOK() *DeleteStorageDiskOK {
	return &DeleteStorageDiskOK{}
}

/*
DeleteStorageDiskOK describes a response with status code 200, with default header values.

A successful response.
*/
type DeleteStorageDiskOK struct {
	Payload models.DeleteStorageDiskResponse
}

// IsSuccess returns true when this delete storage disk o k response has a 2xx status code
func (o *DeleteStorageDiskOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete storage disk o k response has a 3xx status code
func (o *DeleteStorageDiskOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete storage disk o k response has a 4xx status code
func (o *DeleteStorageDiskOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete storage disk o k response has a 5xx status code
func (o *DeleteStorageDiskOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete storage disk o k response a status code equal to that given
func (o *DeleteStorageDiskOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete storage disk o k response
func (o *DeleteStorageDiskOK) Code() int {
	return 200
}

func (o *DeleteStorageDiskOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/projects/{projectId}/disks/{id}][%d] deleteStorageDiskOK  %+v", 200, o.Payload)
}

func (o *DeleteStorageDiskOK) String() string {
	return fmt.Sprintf("[DELETE /v1/projects/{projectId}/disks/{id}][%d] deleteStorageDiskOK  %+v", 200, o.Payload)
}

func (o *DeleteStorageDiskOK) GetPayload() models.DeleteStorageDiskResponse {
	return o.Payload
}

func (o *DeleteStorageDiskOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteStorageDiskDefault creates a DeleteStorageDiskDefault with default headers values
func NewDeleteStorageDiskDefault(code int) *DeleteStorageDiskDefault {
	return &DeleteStorageDiskDefault{
		_statusCode: code,
	}
}

/*
DeleteStorageDiskDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type DeleteStorageDiskDefault struct {
	_statusCode int

	Payload *models.Status
}

// IsSuccess returns true when this delete storage disk default response has a 2xx status code
func (o *DeleteStorageDiskDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this delete storage disk default response has a 3xx status code
func (o *DeleteStorageDiskDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this delete storage disk default response has a 4xx status code
func (o *DeleteStorageDiskDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this delete storage disk default response has a 5xx status code
func (o *DeleteStorageDiskDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this delete storage disk default response a status code equal to that given
func (o *DeleteStorageDiskDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the delete storage disk default response
func (o *DeleteStorageDiskDefault) Code() int {
	return o._statusCode
}

func (o *DeleteStorageDiskDefault) Error() string {
	return fmt.Sprintf("[DELETE /v1/projects/{projectId}/disks/{id}][%d] DeleteStorageDisk default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteStorageDiskDefault) String() string {
	return fmt.Sprintf("[DELETE /v1/projects/{projectId}/disks/{id}][%d] DeleteStorageDisk default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteStorageDiskDefault) GetPayload() *models.Status {
	return o.Payload
}

func (o *DeleteStorageDiskDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
