// Code generated by go-swagger; DO NOT EDIT.

package virtual_machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCreateVMSnapshotParams creates a new CreateVMSnapshotParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateVMSnapshotParams() *CreateVMSnapshotParams {
	return &CreateVMSnapshotParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateVMSnapshotParamsWithTimeout creates a new CreateVMSnapshotParams object
// with the ability to set a timeout on a request.
func NewCreateVMSnapshotParamsWithTimeout(timeout time.Duration) *CreateVMSnapshotParams {
	return &CreateVMSnapshotParams{
		timeout: timeout,
	}
}

// NewCreateVMSnapshotParamsWithContext creates a new CreateVMSnapshotParams object
// with the ability to set a context for a request.
func NewCreateVMSnapshotParamsWithContext(ctx context.Context) *CreateVMSnapshotParams {
	return &CreateVMSnapshotParams{
		Context: ctx,
	}
}

// NewCreateVMSnapshotParamsWithHTTPClient creates a new CreateVMSnapshotParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateVMSnapshotParamsWithHTTPClient(client *http.Client) *CreateVMSnapshotParams {
	return &CreateVMSnapshotParams{
		HTTPClient: client,
	}
}

/*
CreateVMSnapshotParams contains all the parameters to send to the API endpoint

	for the create VM snapshot operation.

	Typically these are written to a http.Request.
*/
type CreateVMSnapshotParams struct {

	// ID.
	ID string

	// ProjectID.
	ProjectID string

	// SnapshotID.
	SnapshotID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create VM snapshot params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateVMSnapshotParams) WithDefaults() *CreateVMSnapshotParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create VM snapshot params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateVMSnapshotParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create VM snapshot params
func (o *CreateVMSnapshotParams) WithTimeout(timeout time.Duration) *CreateVMSnapshotParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create VM snapshot params
func (o *CreateVMSnapshotParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create VM snapshot params
func (o *CreateVMSnapshotParams) WithContext(ctx context.Context) *CreateVMSnapshotParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create VM snapshot params
func (o *CreateVMSnapshotParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create VM snapshot params
func (o *CreateVMSnapshotParams) WithHTTPClient(client *http.Client) *CreateVMSnapshotParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create VM snapshot params
func (o *CreateVMSnapshotParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the create VM snapshot params
func (o *CreateVMSnapshotParams) WithID(id string) *CreateVMSnapshotParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the create VM snapshot params
func (o *CreateVMSnapshotParams) SetID(id string) {
	o.ID = id
}

// WithProjectID adds the projectID to the create VM snapshot params
func (o *CreateVMSnapshotParams) WithProjectID(projectID string) *CreateVMSnapshotParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the create VM snapshot params
func (o *CreateVMSnapshotParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WithSnapshotID adds the snapshotID to the create VM snapshot params
func (o *CreateVMSnapshotParams) WithSnapshotID(snapshotID string) *CreateVMSnapshotParams {
	o.SetSnapshotID(snapshotID)
	return o
}

// SetSnapshotID adds the snapshotId to the create VM snapshot params
func (o *CreateVMSnapshotParams) SetSnapshotID(snapshotID string) {
	o.SnapshotID = snapshotID
}

// WriteToRequest writes these params to a swagger request
func (o *CreateVMSnapshotParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param projectId
	if err := r.SetPathParam("projectId", o.ProjectID); err != nil {
		return err
	}

	// query param snapshotId
	qrSnapshotID := o.SnapshotID
	qSnapshotID := qrSnapshotID
	if qSnapshotID != "" {

		if err := r.SetQueryParam("snapshotId", qSnapshotID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
