// Code generated by go-swagger; DO NOT EDIT.

package virtual_machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/CudoVentures/terraform-provider-cudo/internal/models"
)

// CreateVMSnapshotReader is a Reader for the CreateVMSnapshot structure.
type CreateVMSnapshotReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateVMSnapshotReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateVMSnapshotOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCreateVMSnapshotDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreateVMSnapshotOK creates a CreateVMSnapshotOK with default headers values
func NewCreateVMSnapshotOK() *CreateVMSnapshotOK {
	return &CreateVMSnapshotOK{}
}

/*
CreateVMSnapshotOK describes a response with status code 200, with default header values.

A successful response.
*/
type CreateVMSnapshotOK struct {
	Payload models.CreateVMSnapshotResponse
}

// IsSuccess returns true when this create Vm snapshot o k response has a 2xx status code
func (o *CreateVMSnapshotOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create Vm snapshot o k response has a 3xx status code
func (o *CreateVMSnapshotOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create Vm snapshot o k response has a 4xx status code
func (o *CreateVMSnapshotOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create Vm snapshot o k response has a 5xx status code
func (o *CreateVMSnapshotOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create Vm snapshot o k response a status code equal to that given
func (o *CreateVMSnapshotOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the create Vm snapshot o k response
func (o *CreateVMSnapshotOK) Code() int {
	return 200
}

func (o *CreateVMSnapshotOK) Error() string {
	return fmt.Sprintf("[POST /v1/projects/{projectId}/vms/{id}/snapshots][%d] createVmSnapshotOK  %+v", 200, o.Payload)
}

func (o *CreateVMSnapshotOK) String() string {
	return fmt.Sprintf("[POST /v1/projects/{projectId}/vms/{id}/snapshots][%d] createVmSnapshotOK  %+v", 200, o.Payload)
}

func (o *CreateVMSnapshotOK) GetPayload() models.CreateVMSnapshotResponse {
	return o.Payload
}

func (o *CreateVMSnapshotOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateVMSnapshotDefault creates a CreateVMSnapshotDefault with default headers values
func NewCreateVMSnapshotDefault(code int) *CreateVMSnapshotDefault {
	return &CreateVMSnapshotDefault{
		_statusCode: code,
	}
}

/*
CreateVMSnapshotDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type CreateVMSnapshotDefault struct {
	_statusCode int

	Payload *models.Status
}

// IsSuccess returns true when this create VM snapshot default response has a 2xx status code
func (o *CreateVMSnapshotDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this create VM snapshot default response has a 3xx status code
func (o *CreateVMSnapshotDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this create VM snapshot default response has a 4xx status code
func (o *CreateVMSnapshotDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this create VM snapshot default response has a 5xx status code
func (o *CreateVMSnapshotDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this create VM snapshot default response a status code equal to that given
func (o *CreateVMSnapshotDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the create VM snapshot default response
func (o *CreateVMSnapshotDefault) Code() int {
	return o._statusCode
}

func (o *CreateVMSnapshotDefault) Error() string {
	return fmt.Sprintf("[POST /v1/projects/{projectId}/vms/{id}/snapshots][%d] CreateVMSnapshot default  %+v", o._statusCode, o.Payload)
}

func (o *CreateVMSnapshotDefault) String() string {
	return fmt.Sprintf("[POST /v1/projects/{projectId}/vms/{id}/snapshots][%d] CreateVMSnapshot default  %+v", o._statusCode, o.Payload)
}

func (o *CreateVMSnapshotDefault) GetPayload() *models.Status {
	return o.Payload
}

func (o *CreateVMSnapshotDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
