// Code generated by go-swagger; DO NOT EDIT.

package virtual_machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCreateDiskSnapshotParams creates a new CreateDiskSnapshotParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateDiskSnapshotParams() *CreateDiskSnapshotParams {
	return &CreateDiskSnapshotParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateDiskSnapshotParamsWithTimeout creates a new CreateDiskSnapshotParams object
// with the ability to set a timeout on a request.
func NewCreateDiskSnapshotParamsWithTimeout(timeout time.Duration) *CreateDiskSnapshotParams {
	return &CreateDiskSnapshotParams{
		timeout: timeout,
	}
}

// NewCreateDiskSnapshotParamsWithContext creates a new CreateDiskSnapshotParams object
// with the ability to set a context for a request.
func NewCreateDiskSnapshotParamsWithContext(ctx context.Context) *CreateDiskSnapshotParams {
	return &CreateDiskSnapshotParams{
		Context: ctx,
	}
}

// NewCreateDiskSnapshotParamsWithHTTPClient creates a new CreateDiskSnapshotParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateDiskSnapshotParamsWithHTTPClient(client *http.Client) *CreateDiskSnapshotParams {
	return &CreateDiskSnapshotParams{
		HTTPClient: client,
	}
}

/*
CreateDiskSnapshotParams contains all the parameters to send to the API endpoint

	for the create disk snapshot operation.

	Typically these are written to a http.Request.
*/
type CreateDiskSnapshotParams struct {

	// ID.
	ID string

	// ProjectID.
	ProjectID string

	// SnapshotID.
	SnapshotID string

	// VMID.
	VMID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create disk snapshot params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateDiskSnapshotParams) WithDefaults() *CreateDiskSnapshotParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create disk snapshot params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateDiskSnapshotParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create disk snapshot params
func (o *CreateDiskSnapshotParams) WithTimeout(timeout time.Duration) *CreateDiskSnapshotParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create disk snapshot params
func (o *CreateDiskSnapshotParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create disk snapshot params
func (o *CreateDiskSnapshotParams) WithContext(ctx context.Context) *CreateDiskSnapshotParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create disk snapshot params
func (o *CreateDiskSnapshotParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create disk snapshot params
func (o *CreateDiskSnapshotParams) WithHTTPClient(client *http.Client) *CreateDiskSnapshotParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create disk snapshot params
func (o *CreateDiskSnapshotParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the create disk snapshot params
func (o *CreateDiskSnapshotParams) WithID(id string) *CreateDiskSnapshotParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the create disk snapshot params
func (o *CreateDiskSnapshotParams) SetID(id string) {
	o.ID = id
}

// WithProjectID adds the projectID to the create disk snapshot params
func (o *CreateDiskSnapshotParams) WithProjectID(projectID string) *CreateDiskSnapshotParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the create disk snapshot params
func (o *CreateDiskSnapshotParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WithSnapshotID adds the snapshotID to the create disk snapshot params
func (o *CreateDiskSnapshotParams) WithSnapshotID(snapshotID string) *CreateDiskSnapshotParams {
	o.SetSnapshotID(snapshotID)
	return o
}

// SetSnapshotID adds the snapshotId to the create disk snapshot params
func (o *CreateDiskSnapshotParams) SetSnapshotID(snapshotID string) {
	o.SnapshotID = snapshotID
}

// WithVMID adds the vMID to the create disk snapshot params
func (o *CreateDiskSnapshotParams) WithVMID(vMID string) *CreateDiskSnapshotParams {
	o.SetVMID(vMID)
	return o
}

// SetVMID adds the vmId to the create disk snapshot params
func (o *CreateDiskSnapshotParams) SetVMID(vMID string) {
	o.VMID = vMID
}

// WriteToRequest writes these params to a swagger request
func (o *CreateDiskSnapshotParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param projectId
	if err := r.SetPathParam("projectId", o.ProjectID); err != nil {
		return err
	}

	// query param snapshotId
	qrSnapshotID := o.SnapshotID
	qSnapshotID := qrSnapshotID
	if qSnapshotID != "" {

		if err := r.SetQueryParam("snapshotId", qSnapshotID); err != nil {
			return err
		}
	}

	// query param vmId
	qrVMID := o.VMID
	qVMID := qrVMID
	if qVMID != "" {

		if err := r.SetQueryParam("vmId", qVMID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
