// Code generated by go-swagger; DO NOT EDIT.

package virtual_machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/CudoVentures/terraform-provider-cudo/internal/models"
)

// DeletePrivateVMImageReader is a Reader for the DeletePrivateVMImage structure.
type DeletePrivateVMImageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeletePrivateVMImageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeletePrivateVMImageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDeletePrivateVMImageDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeletePrivateVMImageOK creates a DeletePrivateVMImageOK with default headers values
func NewDeletePrivateVMImageOK() *DeletePrivateVMImageOK {
	return &DeletePrivateVMImageOK{}
}

/*
DeletePrivateVMImageOK describes a response with status code 200, with default header values.

A successful response.
*/
type DeletePrivateVMImageOK struct {
	Payload models.DeletePrivateVMImageResponse
}

// IsSuccess returns true when this delete private Vm image o k response has a 2xx status code
func (o *DeletePrivateVMImageOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete private Vm image o k response has a 3xx status code
func (o *DeletePrivateVMImageOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete private Vm image o k response has a 4xx status code
func (o *DeletePrivateVMImageOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete private Vm image o k response has a 5xx status code
func (o *DeletePrivateVMImageOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete private Vm image o k response a status code equal to that given
func (o *DeletePrivateVMImageOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete private Vm image o k response
func (o *DeletePrivateVMImageOK) Code() int {
	return 200
}

func (o *DeletePrivateVMImageOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/projects/{projectId}/images/{id}][%d] deletePrivateVmImageOK  %+v", 200, o.Payload)
}

func (o *DeletePrivateVMImageOK) String() string {
	return fmt.Sprintf("[DELETE /v1/projects/{projectId}/images/{id}][%d] deletePrivateVmImageOK  %+v", 200, o.Payload)
}

func (o *DeletePrivateVMImageOK) GetPayload() models.DeletePrivateVMImageResponse {
	return o.Payload
}

func (o *DeletePrivateVMImageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeletePrivateVMImageDefault creates a DeletePrivateVMImageDefault with default headers values
func NewDeletePrivateVMImageDefault(code int) *DeletePrivateVMImageDefault {
	return &DeletePrivateVMImageDefault{
		_statusCode: code,
	}
}

/*
DeletePrivateVMImageDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type DeletePrivateVMImageDefault struct {
	_statusCode int

	Payload *models.Status
}

// IsSuccess returns true when this delete private VM image default response has a 2xx status code
func (o *DeletePrivateVMImageDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this delete private VM image default response has a 3xx status code
func (o *DeletePrivateVMImageDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this delete private VM image default response has a 4xx status code
func (o *DeletePrivateVMImageDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this delete private VM image default response has a 5xx status code
func (o *DeletePrivateVMImageDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this delete private VM image default response a status code equal to that given
func (o *DeletePrivateVMImageDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the delete private VM image default response
func (o *DeletePrivateVMImageDefault) Code() int {
	return o._statusCode
}

func (o *DeletePrivateVMImageDefault) Error() string {
	return fmt.Sprintf("[DELETE /v1/projects/{projectId}/images/{id}][%d] DeletePrivateVMImage default  %+v", o._statusCode, o.Payload)
}

func (o *DeletePrivateVMImageDefault) String() string {
	return fmt.Sprintf("[DELETE /v1/projects/{projectId}/images/{id}][%d] DeletePrivateVMImage default  %+v", o._statusCode, o.Payload)
}

func (o *DeletePrivateVMImageDefault) GetPayload() *models.Status {
	return o.Payload
}

func (o *DeletePrivateVMImageDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
