// Code generated by go-swagger; DO NOT EDIT.

package virtual_machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/CudoVentures/terraform-provider-cudo/internal/models"
)

// GetPrivateVMImageReader is a Reader for the GetPrivateVMImage structure.
type GetPrivateVMImageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPrivateVMImageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPrivateVMImageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetPrivateVMImageDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetPrivateVMImageOK creates a GetPrivateVMImageOK with default headers values
func NewGetPrivateVMImageOK() *GetPrivateVMImageOK {
	return &GetPrivateVMImageOK{}
}

/*
GetPrivateVMImageOK describes a response with status code 200, with default header values.

A successful response.
*/
type GetPrivateVMImageOK struct {
	Payload *models.GetPrivateVMImageResponse
}

// IsSuccess returns true when this get private Vm image o k response has a 2xx status code
func (o *GetPrivateVMImageOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get private Vm image o k response has a 3xx status code
func (o *GetPrivateVMImageOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get private Vm image o k response has a 4xx status code
func (o *GetPrivateVMImageOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get private Vm image o k response has a 5xx status code
func (o *GetPrivateVMImageOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get private Vm image o k response a status code equal to that given
func (o *GetPrivateVMImageOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get private Vm image o k response
func (o *GetPrivateVMImageOK) Code() int {
	return 200
}

func (o *GetPrivateVMImageOK) Error() string {
	return fmt.Sprintf("[GET /v1/projects/{projectId}/images/{id}][%d] getPrivateVmImageOK  %+v", 200, o.Payload)
}

func (o *GetPrivateVMImageOK) String() string {
	return fmt.Sprintf("[GET /v1/projects/{projectId}/images/{id}][%d] getPrivateVmImageOK  %+v", 200, o.Payload)
}

func (o *GetPrivateVMImageOK) GetPayload() *models.GetPrivateVMImageResponse {
	return o.Payload
}

func (o *GetPrivateVMImageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetPrivateVMImageResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPrivateVMImageDefault creates a GetPrivateVMImageDefault with default headers values
func NewGetPrivateVMImageDefault(code int) *GetPrivateVMImageDefault {
	return &GetPrivateVMImageDefault{
		_statusCode: code,
	}
}

/*
GetPrivateVMImageDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type GetPrivateVMImageDefault struct {
	_statusCode int

	Payload *models.Status
}

// IsSuccess returns true when this get private VM image default response has a 2xx status code
func (o *GetPrivateVMImageDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get private VM image default response has a 3xx status code
func (o *GetPrivateVMImageDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get private VM image default response has a 4xx status code
func (o *GetPrivateVMImageDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get private VM image default response has a 5xx status code
func (o *GetPrivateVMImageDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get private VM image default response a status code equal to that given
func (o *GetPrivateVMImageDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get private VM image default response
func (o *GetPrivateVMImageDefault) Code() int {
	return o._statusCode
}

func (o *GetPrivateVMImageDefault) Error() string {
	return fmt.Sprintf("[GET /v1/projects/{projectId}/images/{id}][%d] GetPrivateVMImage default  %+v", o._statusCode, o.Payload)
}

func (o *GetPrivateVMImageDefault) String() string {
	return fmt.Sprintf("[GET /v1/projects/{projectId}/images/{id}][%d] GetPrivateVMImage default  %+v", o._statusCode, o.Payload)
}

func (o *GetPrivateVMImageDefault) GetPayload() *models.Status {
	return o.Payload
}

func (o *GetPrivateVMImageDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
