// Code generated by go-swagger; DO NOT EDIT.

package virtual_machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPrivateVMImageParams creates a new GetPrivateVMImageParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetPrivateVMImageParams() *GetPrivateVMImageParams {
	return &GetPrivateVMImageParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetPrivateVMImageParamsWithTimeout creates a new GetPrivateVMImageParams object
// with the ability to set a timeout on a request.
func NewGetPrivateVMImageParamsWithTimeout(timeout time.Duration) *GetPrivateVMImageParams {
	return &GetPrivateVMImageParams{
		timeout: timeout,
	}
}

// NewGetPrivateVMImageParamsWithContext creates a new GetPrivateVMImageParams object
// with the ability to set a context for a request.
func NewGetPrivateVMImageParamsWithContext(ctx context.Context) *GetPrivateVMImageParams {
	return &GetPrivateVMImageParams{
		Context: ctx,
	}
}

// NewGetPrivateVMImageParamsWithHTTPClient creates a new GetPrivateVMImageParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetPrivateVMImageParamsWithHTTPClient(client *http.Client) *GetPrivateVMImageParams {
	return &GetPrivateVMImageParams{
		HTTPClient: client,
	}
}

/*
GetPrivateVMImageParams contains all the parameters to send to the API endpoint

	for the get private VM image operation.

	Typically these are written to a http.Request.
*/
type GetPrivateVMImageParams struct {

	// ID.
	ID string

	// ProjectID.
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get private VM image params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPrivateVMImageParams) WithDefaults() *GetPrivateVMImageParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get private VM image params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPrivateVMImageParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get private VM image params
func (o *GetPrivateVMImageParams) WithTimeout(timeout time.Duration) *GetPrivateVMImageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get private VM image params
func (o *GetPrivateVMImageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get private VM image params
func (o *GetPrivateVMImageParams) WithContext(ctx context.Context) *GetPrivateVMImageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get private VM image params
func (o *GetPrivateVMImageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get private VM image params
func (o *GetPrivateVMImageParams) WithHTTPClient(client *http.Client) *GetPrivateVMImageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get private VM image params
func (o *GetPrivateVMImageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get private VM image params
func (o *GetPrivateVMImageParams) WithID(id string) *GetPrivateVMImageParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get private VM image params
func (o *GetPrivateVMImageParams) SetID(id string) {
	o.ID = id
}

// WithProjectID adds the projectID to the get private VM image params
func (o *GetPrivateVMImageParams) WithProjectID(projectID string) *GetPrivateVMImageParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the get private VM image params
func (o *GetPrivateVMImageParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *GetPrivateVMImageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param projectId
	if err := r.SetPathParam("projectId", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
