// Code generated by go-swagger; DO NOT EDIT.

package virtual_machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/CudoVentures/terraform-provider-cudo/internal/models"
)

// ListVMDataCentersReader is a Reader for the ListVMDataCenters structure.
type ListVMDataCentersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListVMDataCentersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListVMDataCentersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListVMDataCentersDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListVMDataCentersOK creates a ListVMDataCentersOK with default headers values
func NewListVMDataCentersOK() *ListVMDataCentersOK {
	return &ListVMDataCentersOK{}
}

/*
ListVMDataCentersOK describes a response with status code 200, with default header values.

A successful response.
*/
type ListVMDataCentersOK struct {
	Payload *models.ListVMDataCentersResponse
}

// IsSuccess returns true when this list Vm data centers o k response has a 2xx status code
func (o *ListVMDataCentersOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list Vm data centers o k response has a 3xx status code
func (o *ListVMDataCentersOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list Vm data centers o k response has a 4xx status code
func (o *ListVMDataCentersOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list Vm data centers o k response has a 5xx status code
func (o *ListVMDataCentersOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list Vm data centers o k response a status code equal to that given
func (o *ListVMDataCentersOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list Vm data centers o k response
func (o *ListVMDataCentersOK) Code() int {
	return 200
}

func (o *ListVMDataCentersOK) Error() string {
	return fmt.Sprintf("[GET /v1/vms/data-centers][%d] listVmDataCentersOK  %+v", 200, o.Payload)
}

func (o *ListVMDataCentersOK) String() string {
	return fmt.Sprintf("[GET /v1/vms/data-centers][%d] listVmDataCentersOK  %+v", 200, o.Payload)
}

func (o *ListVMDataCentersOK) GetPayload() *models.ListVMDataCentersResponse {
	return o.Payload
}

func (o *ListVMDataCentersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ListVMDataCentersResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListVMDataCentersDefault creates a ListVMDataCentersDefault with default headers values
func NewListVMDataCentersDefault(code int) *ListVMDataCentersDefault {
	return &ListVMDataCentersDefault{
		_statusCode: code,
	}
}

/*
ListVMDataCentersDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ListVMDataCentersDefault struct {
	_statusCode int

	Payload *models.Status
}

// IsSuccess returns true when this list VM data centers default response has a 2xx status code
func (o *ListVMDataCentersDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this list VM data centers default response has a 3xx status code
func (o *ListVMDataCentersDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this list VM data centers default response has a 4xx status code
func (o *ListVMDataCentersDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this list VM data centers default response has a 5xx status code
func (o *ListVMDataCentersDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this list VM data centers default response a status code equal to that given
func (o *ListVMDataCentersDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the list VM data centers default response
func (o *ListVMDataCentersDefault) Code() int {
	return o._statusCode
}

func (o *ListVMDataCentersDefault) Error() string {
	return fmt.Sprintf("[GET /v1/vms/data-centers][%d] ListVMDataCenters default  %+v", o._statusCode, o.Payload)
}

func (o *ListVMDataCentersDefault) String() string {
	return fmt.Sprintf("[GET /v1/vms/data-centers][%d] ListVMDataCenters default  %+v", o._statusCode, o.Payload)
}

func (o *ListVMDataCentersDefault) GetPayload() *models.Status {
	return o.Payload
}

func (o *ListVMDataCentersDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
