// Code generated by go-swagger; DO NOT EDIT.

package virtual_machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/CudoVentures/terraform-provider-cudo/internal/models"
)

// ListVMSnapshotsReader is a Reader for the ListVMSnapshots structure.
type ListVMSnapshotsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListVMSnapshotsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListVMSnapshotsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListVMSnapshotsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListVMSnapshotsOK creates a ListVMSnapshotsOK with default headers values
func NewListVMSnapshotsOK() *ListVMSnapshotsOK {
	return &ListVMSnapshotsOK{}
}

/*
ListVMSnapshotsOK describes a response with status code 200, with default header values.

A successful response.
*/
type ListVMSnapshotsOK struct {
	Payload *models.ListVMSnapshotsResponse
}

// IsSuccess returns true when this list Vm snapshots o k response has a 2xx status code
func (o *ListVMSnapshotsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list Vm snapshots o k response has a 3xx status code
func (o *ListVMSnapshotsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list Vm snapshots o k response has a 4xx status code
func (o *ListVMSnapshotsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list Vm snapshots o k response has a 5xx status code
func (o *ListVMSnapshotsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list Vm snapshots o k response a status code equal to that given
func (o *ListVMSnapshotsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list Vm snapshots o k response
func (o *ListVMSnapshotsOK) Code() int {
	return 200
}

func (o *ListVMSnapshotsOK) Error() string {
	return fmt.Sprintf("[GET /v1/projects/{projectId}/vms/{id}/snapshots][%d] listVmSnapshotsOK  %+v", 200, o.Payload)
}

func (o *ListVMSnapshotsOK) String() string {
	return fmt.Sprintf("[GET /v1/projects/{projectId}/vms/{id}/snapshots][%d] listVmSnapshotsOK  %+v", 200, o.Payload)
}

func (o *ListVMSnapshotsOK) GetPayload() *models.ListVMSnapshotsResponse {
	return o.Payload
}

func (o *ListVMSnapshotsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ListVMSnapshotsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListVMSnapshotsDefault creates a ListVMSnapshotsDefault with default headers values
func NewListVMSnapshotsDefault(code int) *ListVMSnapshotsDefault {
	return &ListVMSnapshotsDefault{
		_statusCode: code,
	}
}

/*
ListVMSnapshotsDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ListVMSnapshotsDefault struct {
	_statusCode int

	Payload *models.Status
}

// IsSuccess returns true when this list VM snapshots default response has a 2xx status code
func (o *ListVMSnapshotsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this list VM snapshots default response has a 3xx status code
func (o *ListVMSnapshotsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this list VM snapshots default response has a 4xx status code
func (o *ListVMSnapshotsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this list VM snapshots default response has a 5xx status code
func (o *ListVMSnapshotsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this list VM snapshots default response a status code equal to that given
func (o *ListVMSnapshotsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the list VM snapshots default response
func (o *ListVMSnapshotsDefault) Code() int {
	return o._statusCode
}

func (o *ListVMSnapshotsDefault) Error() string {
	return fmt.Sprintf("[GET /v1/projects/{projectId}/vms/{id}/snapshots][%d] ListVMSnapshots default  %+v", o._statusCode, o.Payload)
}

func (o *ListVMSnapshotsDefault) String() string {
	return fmt.Sprintf("[GET /v1/projects/{projectId}/vms/{id}/snapshots][%d] ListVMSnapshots default  %+v", o._statusCode, o.Payload)
}

func (o *ListVMSnapshotsDefault) GetPayload() *models.Status {
	return o.Payload
}

func (o *ListVMSnapshotsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
