// Code generated by go-swagger; DO NOT EDIT.

package virtual_machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewListVMMachineTypesParams creates a new ListVMMachineTypesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListVMMachineTypesParams() *ListVMMachineTypesParams {
	return &ListVMMachineTypesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListVMMachineTypesParamsWithTimeout creates a new ListVMMachineTypesParams object
// with the ability to set a timeout on a request.
func NewListVMMachineTypesParamsWithTimeout(timeout time.Duration) *ListVMMachineTypesParams {
	return &ListVMMachineTypesParams{
		timeout: timeout,
	}
}

// NewListVMMachineTypesParamsWithContext creates a new ListVMMachineTypesParams object
// with the ability to set a context for a request.
func NewListVMMachineTypesParamsWithContext(ctx context.Context) *ListVMMachineTypesParams {
	return &ListVMMachineTypesParams{
		Context: ctx,
	}
}

// NewListVMMachineTypesParamsWithHTTPClient creates a new ListVMMachineTypesParams object
// with the ability to set a custom HTTPClient for a request.
func NewListVMMachineTypesParamsWithHTTPClient(client *http.Client) *ListVMMachineTypesParams {
	return &ListVMMachineTypesParams{
		HTTPClient: client,
	}
}

/*
ListVMMachineTypesParams contains all the parameters to send to the API endpoint

	for the list VM machine types operation.

	Typically these are written to a http.Request.
*/
type ListVMMachineTypesParams struct {

	// CPUModel.
	CPUModel *string

	// DataCenterID.
	DataCenterID *string

	// Gpu.
	//
	// Format: int32
	Gpu *int32

	// GpuModel.
	GpuModel *string

	// MemoryGib.
	//
	// Format: int32
	MemoryGib int32

	// OrderBy.
	OrderBy *string

	// PageNumber.
	//
	// Format: int32
	PageNumber *int32

	// PageSize.
	//
	// Format: int32
	PageSize *int32

	// PublicIPV4.
	PublicIPV4 *bool

	// RegionID.
	RegionID *string

	// StorageGib.
	//
	// Format: int32
	StorageGib *int32

	// Vcpu.
	//
	// Format: int32
	Vcpu int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list VM machine types params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListVMMachineTypesParams) WithDefaults() *ListVMMachineTypesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list VM machine types params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListVMMachineTypesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list VM machine types params
func (o *ListVMMachineTypesParams) WithTimeout(timeout time.Duration) *ListVMMachineTypesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list VM machine types params
func (o *ListVMMachineTypesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list VM machine types params
func (o *ListVMMachineTypesParams) WithContext(ctx context.Context) *ListVMMachineTypesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list VM machine types params
func (o *ListVMMachineTypesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list VM machine types params
func (o *ListVMMachineTypesParams) WithHTTPClient(client *http.Client) *ListVMMachineTypesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list VM machine types params
func (o *ListVMMachineTypesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCPUModel adds the cPUModel to the list VM machine types params
func (o *ListVMMachineTypesParams) WithCPUModel(cPUModel *string) *ListVMMachineTypesParams {
	o.SetCPUModel(cPUModel)
	return o
}

// SetCPUModel adds the cpuModel to the list VM machine types params
func (o *ListVMMachineTypesParams) SetCPUModel(cPUModel *string) {
	o.CPUModel = cPUModel
}

// WithDataCenterID adds the dataCenterID to the list VM machine types params
func (o *ListVMMachineTypesParams) WithDataCenterID(dataCenterID *string) *ListVMMachineTypesParams {
	o.SetDataCenterID(dataCenterID)
	return o
}

// SetDataCenterID adds the dataCenterId to the list VM machine types params
func (o *ListVMMachineTypesParams) SetDataCenterID(dataCenterID *string) {
	o.DataCenterID = dataCenterID
}

// WithGpu adds the gpu to the list VM machine types params
func (o *ListVMMachineTypesParams) WithGpu(gpu *int32) *ListVMMachineTypesParams {
	o.SetGpu(gpu)
	return o
}

// SetGpu adds the gpu to the list VM machine types params
func (o *ListVMMachineTypesParams) SetGpu(gpu *int32) {
	o.Gpu = gpu
}

// WithGpuModel adds the gpuModel to the list VM machine types params
func (o *ListVMMachineTypesParams) WithGpuModel(gpuModel *string) *ListVMMachineTypesParams {
	o.SetGpuModel(gpuModel)
	return o
}

// SetGpuModel adds the gpuModel to the list VM machine types params
func (o *ListVMMachineTypesParams) SetGpuModel(gpuModel *string) {
	o.GpuModel = gpuModel
}

// WithMemoryGib adds the memoryGib to the list VM machine types params
func (o *ListVMMachineTypesParams) WithMemoryGib(memoryGib int32) *ListVMMachineTypesParams {
	o.SetMemoryGib(memoryGib)
	return o
}

// SetMemoryGib adds the memoryGib to the list VM machine types params
func (o *ListVMMachineTypesParams) SetMemoryGib(memoryGib int32) {
	o.MemoryGib = memoryGib
}

// WithOrderBy adds the orderBy to the list VM machine types params
func (o *ListVMMachineTypesParams) WithOrderBy(orderBy *string) *ListVMMachineTypesParams {
	o.SetOrderBy(orderBy)
	return o
}

// SetOrderBy adds the orderBy to the list VM machine types params
func (o *ListVMMachineTypesParams) SetOrderBy(orderBy *string) {
	o.OrderBy = orderBy
}

// WithPageNumber adds the pageNumber to the list VM machine types params
func (o *ListVMMachineTypesParams) WithPageNumber(pageNumber *int32) *ListVMMachineTypesParams {
	o.SetPageNumber(pageNumber)
	return o
}

// SetPageNumber adds the pageNumber to the list VM machine types params
func (o *ListVMMachineTypesParams) SetPageNumber(pageNumber *int32) {
	o.PageNumber = pageNumber
}

// WithPageSize adds the pageSize to the list VM machine types params
func (o *ListVMMachineTypesParams) WithPageSize(pageSize *int32) *ListVMMachineTypesParams {
	o.SetPageSize(pageSize)
	return o
}

// SetPageSize adds the pageSize to the list VM machine types params
func (o *ListVMMachineTypesParams) SetPageSize(pageSize *int32) {
	o.PageSize = pageSize
}

// WithPublicIPV4 adds the publicIPV4 to the list VM machine types params
func (o *ListVMMachineTypesParams) WithPublicIPV4(publicIPV4 *bool) *ListVMMachineTypesParams {
	o.SetPublicIPV4(publicIPV4)
	return o
}

// SetPublicIPV4 adds the publicIpv4 to the list VM machine types params
func (o *ListVMMachineTypesParams) SetPublicIPV4(publicIPV4 *bool) {
	o.PublicIPV4 = publicIPV4
}

// WithRegionID adds the regionID to the list VM machine types params
func (o *ListVMMachineTypesParams) WithRegionID(regionID *string) *ListVMMachineTypesParams {
	o.SetRegionID(regionID)
	return o
}

// SetRegionID adds the regionId to the list VM machine types params
func (o *ListVMMachineTypesParams) SetRegionID(regionID *string) {
	o.RegionID = regionID
}

// WithStorageGib adds the storageGib to the list VM machine types params
func (o *ListVMMachineTypesParams) WithStorageGib(storageGib *int32) *ListVMMachineTypesParams {
	o.SetStorageGib(storageGib)
	return o
}

// SetStorageGib adds the storageGib to the list VM machine types params
func (o *ListVMMachineTypesParams) SetStorageGib(storageGib *int32) {
	o.StorageGib = storageGib
}

// WithVcpu adds the vcpu to the list VM machine types params
func (o *ListVMMachineTypesParams) WithVcpu(vcpu int32) *ListVMMachineTypesParams {
	o.SetVcpu(vcpu)
	return o
}

// SetVcpu adds the vcpu to the list VM machine types params
func (o *ListVMMachineTypesParams) SetVcpu(vcpu int32) {
	o.Vcpu = vcpu
}

// WriteToRequest writes these params to a swagger request
func (o *ListVMMachineTypesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.CPUModel != nil {

		// query param cpuModel
		var qrCPUModel string

		if o.CPUModel != nil {
			qrCPUModel = *o.CPUModel
		}
		qCPUModel := qrCPUModel
		if qCPUModel != "" {

			if err := r.SetQueryParam("cpuModel", qCPUModel); err != nil {
				return err
			}
		}
	}

	if o.DataCenterID != nil {

		// query param dataCenterId
		var qrDataCenterID string

		if o.DataCenterID != nil {
			qrDataCenterID = *o.DataCenterID
		}
		qDataCenterID := qrDataCenterID
		if qDataCenterID != "" {

			if err := r.SetQueryParam("dataCenterId", qDataCenterID); err != nil {
				return err
			}
		}
	}

	if o.Gpu != nil {

		// query param gpu
		var qrGpu int32

		if o.Gpu != nil {
			qrGpu = *o.Gpu
		}
		qGpu := swag.FormatInt32(qrGpu)
		if qGpu != "" {

			if err := r.SetQueryParam("gpu", qGpu); err != nil {
				return err
			}
		}
	}

	if o.GpuModel != nil {

		// query param gpuModel
		var qrGpuModel string

		if o.GpuModel != nil {
			qrGpuModel = *o.GpuModel
		}
		qGpuModel := qrGpuModel
		if qGpuModel != "" {

			if err := r.SetQueryParam("gpuModel", qGpuModel); err != nil {
				return err
			}
		}
	}

	// query param memoryGib
	qrMemoryGib := o.MemoryGib
	qMemoryGib := swag.FormatInt32(qrMemoryGib)
	if qMemoryGib != "" {

		if err := r.SetQueryParam("memoryGib", qMemoryGib); err != nil {
			return err
		}
	}

	if o.OrderBy != nil {

		// query param orderBy
		var qrOrderBy string

		if o.OrderBy != nil {
			qrOrderBy = *o.OrderBy
		}
		qOrderBy := qrOrderBy
		if qOrderBy != "" {

			if err := r.SetQueryParam("orderBy", qOrderBy); err != nil {
				return err
			}
		}
	}

	if o.PageNumber != nil {

		// query param pageNumber
		var qrPageNumber int32

		if o.PageNumber != nil {
			qrPageNumber = *o.PageNumber
		}
		qPageNumber := swag.FormatInt32(qrPageNumber)
		if qPageNumber != "" {

			if err := r.SetQueryParam("pageNumber", qPageNumber); err != nil {
				return err
			}
		}
	}

	if o.PageSize != nil {

		// query param pageSize
		var qrPageSize int32

		if o.PageSize != nil {
			qrPageSize = *o.PageSize
		}
		qPageSize := swag.FormatInt32(qrPageSize)
		if qPageSize != "" {

			if err := r.SetQueryParam("pageSize", qPageSize); err != nil {
				return err
			}
		}
	}

	if o.PublicIPV4 != nil {

		// query param publicIpv4
		var qrPublicIPV4 bool

		if o.PublicIPV4 != nil {
			qrPublicIPV4 = *o.PublicIPV4
		}
		qPublicIPV4 := swag.FormatBool(qrPublicIPV4)
		if qPublicIPV4 != "" {

			if err := r.SetQueryParam("publicIpv4", qPublicIPV4); err != nil {
				return err
			}
		}
	}

	if o.RegionID != nil {

		// query param regionId
		var qrRegionID string

		if o.RegionID != nil {
			qrRegionID = *o.RegionID
		}
		qRegionID := qrRegionID
		if qRegionID != "" {

			if err := r.SetQueryParam("regionId", qRegionID); err != nil {
				return err
			}
		}
	}

	if o.StorageGib != nil {

		// query param storageGib
		var qrStorageGib int32

		if o.StorageGib != nil {
			qrStorageGib = *o.StorageGib
		}
		qStorageGib := swag.FormatInt32(qrStorageGib)
		if qStorageGib != "" {

			if err := r.SetQueryParam("storageGib", qStorageGib); err != nil {
				return err
			}
		}
	}

	// query param vcpu
	qrVcpu := o.Vcpu
	qVcpu := swag.FormatInt32(qrVcpu)
	if qVcpu != "" {

		if err := r.SetQueryParam("vcpu", qVcpu); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
