// Code generated by go-swagger; DO NOT EDIT.

package virtual_machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"cudo.org/v1/terraform-provider-cudo/internal/models"
)

// ListInstancesReader is a Reader for the ListInstances structure.
type ListInstancesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListInstancesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListInstancesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListInstancesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListInstancesOK creates a ListInstancesOK with default headers values
func NewListInstancesOK() *ListInstancesOK {
	return &ListInstancesOK{}
}

/*
	ListInstancesOK describes a response with status code 200, with default header values.

A successful response.
*/
type ListInstancesOK struct {
	Payload *models.ListInstancesResponse
}

// IsSuccess returns true when this list instances o k response has a 2xx status code
func (o *ListInstancesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list instances o k response has a 3xx status code
func (o *ListInstancesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list instances o k response has a 4xx status code
func (o *ListInstancesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list instances o k response has a 5xx status code
func (o *ListInstancesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list instances o k response a status code equal to that given
func (o *ListInstancesOK) IsCode(code int) bool {
	return code == 200
}

func (o *ListInstancesOK) Error() string {
	return fmt.Sprintf("[GET /v1/projects/{projectId}/instances][%d] listInstancesOK  %+v", 200, o.Payload)
}

func (o *ListInstancesOK) String() string {
	return fmt.Sprintf("[GET /v1/projects/{projectId}/instances][%d] listInstancesOK  %+v", 200, o.Payload)
}

func (o *ListInstancesOK) GetPayload() *models.ListInstancesResponse {
	return o.Payload
}

func (o *ListInstancesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ListInstancesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListInstancesDefault creates a ListInstancesDefault with default headers values
func NewListInstancesDefault(code int) *ListInstancesDefault {
	return &ListInstancesDefault{
		_statusCode: code,
	}
}

/*
	ListInstancesDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ListInstancesDefault struct {
	_statusCode int

	Payload *models.Status
}

// Code gets the status code for the list instances default response
func (o *ListInstancesDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this list instances default response has a 2xx status code
func (o *ListInstancesDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this list instances default response has a 3xx status code
func (o *ListInstancesDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this list instances default response has a 4xx status code
func (o *ListInstancesDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this list instances default response has a 5xx status code
func (o *ListInstancesDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this list instances default response a status code equal to that given
func (o *ListInstancesDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *ListInstancesDefault) Error() string {
	return fmt.Sprintf("[GET /v1/projects/{projectId}/instances][%d] ListInstances default  %+v", o._statusCode, o.Payload)
}

func (o *ListInstancesDefault) String() string {
	return fmt.Sprintf("[GET /v1/projects/{projectId}/instances][%d] ListInstances default  %+v", o._statusCode, o.Payload)
}

func (o *ListInstancesDefault) GetPayload() *models.Status {
	return o.Payload
}

func (o *ListInstancesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
