// Code generated by go-swagger; DO NOT EDIT.

package virtual_machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListVMDisksParams creates a new ListVMDisksParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListVMDisksParams() *ListVMDisksParams {
	return &ListVMDisksParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListVMDisksParamsWithTimeout creates a new ListVMDisksParams object
// with the ability to set a timeout on a request.
func NewListVMDisksParamsWithTimeout(timeout time.Duration) *ListVMDisksParams {
	return &ListVMDisksParams{
		timeout: timeout,
	}
}

// NewListVMDisksParamsWithContext creates a new ListVMDisksParams object
// with the ability to set a context for a request.
func NewListVMDisksParamsWithContext(ctx context.Context) *ListVMDisksParams {
	return &ListVMDisksParams{
		Context: ctx,
	}
}

// NewListVMDisksParamsWithHTTPClient creates a new ListVMDisksParams object
// with the ability to set a custom HTTPClient for a request.
func NewListVMDisksParamsWithHTTPClient(client *http.Client) *ListVMDisksParams {
	return &ListVMDisksParams{
		HTTPClient: client,
	}
}

/*
ListVMDisksParams contains all the parameters to send to the API endpoint

	for the list VM disks operation.

	Typically these are written to a http.Request.
*/
type ListVMDisksParams struct {

	// ID.
	ID string

	// ProjectID.
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list VM disks params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListVMDisksParams) WithDefaults() *ListVMDisksParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list VM disks params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListVMDisksParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list VM disks params
func (o *ListVMDisksParams) WithTimeout(timeout time.Duration) *ListVMDisksParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list VM disks params
func (o *ListVMDisksParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list VM disks params
func (o *ListVMDisksParams) WithContext(ctx context.Context) *ListVMDisksParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list VM disks params
func (o *ListVMDisksParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list VM disks params
func (o *ListVMDisksParams) WithHTTPClient(client *http.Client) *ListVMDisksParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list VM disks params
func (o *ListVMDisksParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the list VM disks params
func (o *ListVMDisksParams) WithID(id string) *ListVMDisksParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the list VM disks params
func (o *ListVMDisksParams) SetID(id string) {
	o.ID = id
}

// WithProjectID adds the projectID to the list VM disks params
func (o *ListVMDisksParams) WithProjectID(projectID string) *ListVMDisksParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the list VM disks params
func (o *ListVMDisksParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *ListVMDisksParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param projectId
	if err := r.SetPathParam("projectId", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
