// Code generated by go-swagger; DO NOT EDIT.

package virtual_machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewMonitorInstanceParams creates a new MonitorInstanceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewMonitorInstanceParams() *MonitorInstanceParams {
	return &MonitorInstanceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewMonitorInstanceParamsWithTimeout creates a new MonitorInstanceParams object
// with the ability to set a timeout on a request.
func NewMonitorInstanceParamsWithTimeout(timeout time.Duration) *MonitorInstanceParams {
	return &MonitorInstanceParams{
		timeout: timeout,
	}
}

// NewMonitorInstanceParamsWithContext creates a new MonitorInstanceParams object
// with the ability to set a context for a request.
func NewMonitorInstanceParamsWithContext(ctx context.Context) *MonitorInstanceParams {
	return &MonitorInstanceParams{
		Context: ctx,
	}
}

// NewMonitorInstanceParamsWithHTTPClient creates a new MonitorInstanceParams object
// with the ability to set a custom HTTPClient for a request.
func NewMonitorInstanceParamsWithHTTPClient(client *http.Client) *MonitorInstanceParams {
	return &MonitorInstanceParams{
		HTTPClient: client,
	}
}

/*
MonitorInstanceParams contains all the parameters to send to the API endpoint

	for the monitor instance operation.

	Typically these are written to a http.Request.
*/
type MonitorInstanceParams struct {

	// InstanceID.
	InstanceID string

	// ProjectID.
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the monitor instance params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MonitorInstanceParams) WithDefaults() *MonitorInstanceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the monitor instance params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MonitorInstanceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the monitor instance params
func (o *MonitorInstanceParams) WithTimeout(timeout time.Duration) *MonitorInstanceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the monitor instance params
func (o *MonitorInstanceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the monitor instance params
func (o *MonitorInstanceParams) WithContext(ctx context.Context) *MonitorInstanceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the monitor instance params
func (o *MonitorInstanceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the monitor instance params
func (o *MonitorInstanceParams) WithHTTPClient(client *http.Client) *MonitorInstanceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the monitor instance params
func (o *MonitorInstanceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInstanceID adds the instanceID to the monitor instance params
func (o *MonitorInstanceParams) WithInstanceID(instanceID string) *MonitorInstanceParams {
	o.SetInstanceID(instanceID)
	return o
}

// SetInstanceID adds the instanceId to the monitor instance params
func (o *MonitorInstanceParams) SetInstanceID(instanceID string) {
	o.InstanceID = instanceID
}

// WithProjectID adds the projectID to the monitor instance params
func (o *MonitorInstanceParams) WithProjectID(projectID string) *MonitorInstanceParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the monitor instance params
func (o *MonitorInstanceParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *MonitorInstanceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param instanceId
	if err := r.SetPathParam("instanceId", o.InstanceID); err != nil {
		return err
	}

	// path param projectId
	if err := r.SetPathParam("projectId", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
