// Code generated by go-swagger; DO NOT EDIT.

package virtual_machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/CudoVentures/terraform-provider-cudo/internal/models"
)

// MonitorVMReader is a Reader for the MonitorVM structure.
type MonitorVMReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MonitorVMReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewMonitorVMOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewMonitorVMDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewMonitorVMOK creates a MonitorVMOK with default headers values
func NewMonitorVMOK() *MonitorVMOK {
	return &MonitorVMOK{}
}

/*
MonitorVMOK describes a response with status code 200, with default header values.

A successful response.
*/
type MonitorVMOK struct {
	Payload *models.MonitorVMResponse
}

// IsSuccess returns true when this monitor Vm o k response has a 2xx status code
func (o *MonitorVMOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this monitor Vm o k response has a 3xx status code
func (o *MonitorVMOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this monitor Vm o k response has a 4xx status code
func (o *MonitorVMOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this monitor Vm o k response has a 5xx status code
func (o *MonitorVMOK) IsServerError() bool {
	return false
}

// IsCode returns true when this monitor Vm o k response a status code equal to that given
func (o *MonitorVMOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the monitor Vm o k response
func (o *MonitorVMOK) Code() int {
	return 200
}

func (o *MonitorVMOK) Error() string {
	return fmt.Sprintf("[GET /v1/projects/{projectId}/vms/{id}/monitor][%d] monitorVmOK  %+v", 200, o.Payload)
}

func (o *MonitorVMOK) String() string {
	return fmt.Sprintf("[GET /v1/projects/{projectId}/vms/{id}/monitor][%d] monitorVmOK  %+v", 200, o.Payload)
}

func (o *MonitorVMOK) GetPayload() *models.MonitorVMResponse {
	return o.Payload
}

func (o *MonitorVMOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MonitorVMResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMonitorVMDefault creates a MonitorVMDefault with default headers values
func NewMonitorVMDefault(code int) *MonitorVMDefault {
	return &MonitorVMDefault{
		_statusCode: code,
	}
}

/*
MonitorVMDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type MonitorVMDefault struct {
	_statusCode int

	Payload *models.Status
}

// IsSuccess returns true when this monitor VM default response has a 2xx status code
func (o *MonitorVMDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this monitor VM default response has a 3xx status code
func (o *MonitorVMDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this monitor VM default response has a 4xx status code
func (o *MonitorVMDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this monitor VM default response has a 5xx status code
func (o *MonitorVMDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this monitor VM default response a status code equal to that given
func (o *MonitorVMDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the monitor VM default response
func (o *MonitorVMDefault) Code() int {
	return o._statusCode
}

func (o *MonitorVMDefault) Error() string {
	return fmt.Sprintf("[GET /v1/projects/{projectId}/vms/{id}/monitor][%d] MonitorVM default  %+v", o._statusCode, o.Payload)
}

func (o *MonitorVMDefault) String() string {
	return fmt.Sprintf("[GET /v1/projects/{projectId}/vms/{id}/monitor][%d] MonitorVM default  %+v", o._statusCode, o.Payload)
}

func (o *MonitorVMDefault) GetPayload() *models.Status {
	return o.Payload
}

func (o *MonitorVMDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
