// Code generated by go-swagger; DO NOT EDIT.

package virtual_machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"cudo.org/v1/terraform-provider-cudo/internal/models"
)

// MonitorInstanceReader is a Reader for the MonitorInstance structure.
type MonitorInstanceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MonitorInstanceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewMonitorInstanceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewMonitorInstanceDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewMonitorInstanceOK creates a MonitorInstanceOK with default headers values
func NewMonitorInstanceOK() *MonitorInstanceOK {
	return &MonitorInstanceOK{}
}

/*
	MonitorInstanceOK describes a response with status code 200, with default header values.

A successful response.
*/
type MonitorInstanceOK struct {
	Payload *models.MonitorInstanceResponse
}

// IsSuccess returns true when this monitor instance o k response has a 2xx status code
func (o *MonitorInstanceOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this monitor instance o k response has a 3xx status code
func (o *MonitorInstanceOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this monitor instance o k response has a 4xx status code
func (o *MonitorInstanceOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this monitor instance o k response has a 5xx status code
func (o *MonitorInstanceOK) IsServerError() bool {
	return false
}

// IsCode returns true when this monitor instance o k response a status code equal to that given
func (o *MonitorInstanceOK) IsCode(code int) bool {
	return code == 200
}

func (o *MonitorInstanceOK) Error() string {
	return fmt.Sprintf("[GET /v1/projects/{projectId}/instances/{instanceId}/monitor][%d] monitorInstanceOK  %+v", 200, o.Payload)
}

func (o *MonitorInstanceOK) String() string {
	return fmt.Sprintf("[GET /v1/projects/{projectId}/instances/{instanceId}/monitor][%d] monitorInstanceOK  %+v", 200, o.Payload)
}

func (o *MonitorInstanceOK) GetPayload() *models.MonitorInstanceResponse {
	return o.Payload
}

func (o *MonitorInstanceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MonitorInstanceResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMonitorInstanceDefault creates a MonitorInstanceDefault with default headers values
func NewMonitorInstanceDefault(code int) *MonitorInstanceDefault {
	return &MonitorInstanceDefault{
		_statusCode: code,
	}
}

/*
	MonitorInstanceDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type MonitorInstanceDefault struct {
	_statusCode int

	Payload *models.Status
}

// Code gets the status code for the monitor instance default response
func (o *MonitorInstanceDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this monitor instance default response has a 2xx status code
func (o *MonitorInstanceDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this monitor instance default response has a 3xx status code
func (o *MonitorInstanceDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this monitor instance default response has a 4xx status code
func (o *MonitorInstanceDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this monitor instance default response has a 5xx status code
func (o *MonitorInstanceDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this monitor instance default response a status code equal to that given
func (o *MonitorInstanceDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *MonitorInstanceDefault) Error() string {
	return fmt.Sprintf("[GET /v1/projects/{projectId}/instances/{instanceId}/monitor][%d] MonitorInstance default  %+v", o._statusCode, o.Payload)
}

func (o *MonitorInstanceDefault) String() string {
	return fmt.Sprintf("[GET /v1/projects/{projectId}/instances/{instanceId}/monitor][%d] MonitorInstance default  %+v", o._statusCode, o.Payload)
}

func (o *MonitorInstanceDefault) GetPayload() *models.Status {
	return o.Payload
}

func (o *MonitorInstanceDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
