// Code generated by go-swagger; DO NOT EDIT.

package virtual_machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/CudoVentures/terraform-provider-cudo/internal/models"
)

// RevertVMReader is a Reader for the RevertVM structure.
type RevertVMReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RevertVMReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRevertVMOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewRevertVMDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRevertVMOK creates a RevertVMOK with default headers values
func NewRevertVMOK() *RevertVMOK {
	return &RevertVMOK{}
}

/*
RevertVMOK describes a response with status code 200, with default header values.

A successful response.
*/
type RevertVMOK struct {
	Payload models.RevertVMResponse
}

// IsSuccess returns true when this revert Vm o k response has a 2xx status code
func (o *RevertVMOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this revert Vm o k response has a 3xx status code
func (o *RevertVMOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this revert Vm o k response has a 4xx status code
func (o *RevertVMOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this revert Vm o k response has a 5xx status code
func (o *RevertVMOK) IsServerError() bool {
	return false
}

// IsCode returns true when this revert Vm o k response a status code equal to that given
func (o *RevertVMOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the revert Vm o k response
func (o *RevertVMOK) Code() int {
	return 200
}

func (o *RevertVMOK) Error() string {
	return fmt.Sprintf("[POST /v1/projects/{projectId}/vms/{id}/revert][%d] revertVmOK  %+v", 200, o.Payload)
}

func (o *RevertVMOK) String() string {
	return fmt.Sprintf("[POST /v1/projects/{projectId}/vms/{id}/revert][%d] revertVmOK  %+v", 200, o.Payload)
}

func (o *RevertVMOK) GetPayload() models.RevertVMResponse {
	return o.Payload
}

func (o *RevertVMOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRevertVMDefault creates a RevertVMDefault with default headers values
func NewRevertVMDefault(code int) *RevertVMDefault {
	return &RevertVMDefault{
		_statusCode: code,
	}
}

/*
RevertVMDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type RevertVMDefault struct {
	_statusCode int

	Payload *models.Status
}

// IsSuccess returns true when this revert VM default response has a 2xx status code
func (o *RevertVMDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this revert VM default response has a 3xx status code
func (o *RevertVMDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this revert VM default response has a 4xx status code
func (o *RevertVMDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this revert VM default response has a 5xx status code
func (o *RevertVMDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this revert VM default response a status code equal to that given
func (o *RevertVMDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the revert VM default response
func (o *RevertVMDefault) Code() int {
	return o._statusCode
}

func (o *RevertVMDefault) Error() string {
	return fmt.Sprintf("[POST /v1/projects/{projectId}/vms/{id}/revert][%d] RevertVM default  %+v", o._statusCode, o.Payload)
}

func (o *RevertVMDefault) String() string {
	return fmt.Sprintf("[POST /v1/projects/{projectId}/vms/{id}/revert][%d] RevertVM default  %+v", o._statusCode, o.Payload)
}

func (o *RevertVMDefault) GetPayload() *models.Status {
	return o.Payload
}

func (o *RevertVMDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
