// Code generated by go-swagger; DO NOT EDIT.

package virtual_machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewStartInstanceParams creates a new StartInstanceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewStartInstanceParams() *StartInstanceParams {
	return &StartInstanceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewStartInstanceParamsWithTimeout creates a new StartInstanceParams object
// with the ability to set a timeout on a request.
func NewStartInstanceParamsWithTimeout(timeout time.Duration) *StartInstanceParams {
	return &StartInstanceParams{
		timeout: timeout,
	}
}

// NewStartInstanceParamsWithContext creates a new StartInstanceParams object
// with the ability to set a context for a request.
func NewStartInstanceParamsWithContext(ctx context.Context) *StartInstanceParams {
	return &StartInstanceParams{
		Context: ctx,
	}
}

// NewStartInstanceParamsWithHTTPClient creates a new StartInstanceParams object
// with the ability to set a custom HTTPClient for a request.
func NewStartInstanceParamsWithHTTPClient(client *http.Client) *StartInstanceParams {
	return &StartInstanceParams{
		HTTPClient: client,
	}
}

/*
StartInstanceParams contains all the parameters to send to the API endpoint

	for the start instance operation.

	Typically these are written to a http.Request.
*/
type StartInstanceParams struct {

	// InstanceID.
	InstanceID string

	// ProjectID.
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the start instance params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StartInstanceParams) WithDefaults() *StartInstanceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the start instance params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StartInstanceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the start instance params
func (o *StartInstanceParams) WithTimeout(timeout time.Duration) *StartInstanceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the start instance params
func (o *StartInstanceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the start instance params
func (o *StartInstanceParams) WithContext(ctx context.Context) *StartInstanceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the start instance params
func (o *StartInstanceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the start instance params
func (o *StartInstanceParams) WithHTTPClient(client *http.Client) *StartInstanceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the start instance params
func (o *StartInstanceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInstanceID adds the instanceID to the start instance params
func (o *StartInstanceParams) WithInstanceID(instanceID string) *StartInstanceParams {
	o.SetInstanceID(instanceID)
	return o
}

// SetInstanceID adds the instanceId to the start instance params
func (o *StartInstanceParams) SetInstanceID(instanceID string) {
	o.InstanceID = instanceID
}

// WithProjectID adds the projectID to the start instance params
func (o *StartInstanceParams) WithProjectID(projectID string) *StartInstanceParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the start instance params
func (o *StartInstanceParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *StartInstanceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param instanceId
	if err := r.SetPathParam("instanceId", o.InstanceID); err != nil {
		return err
	}

	// path param projectId
	if err := r.SetPathParam("projectId", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
