// Code generated by go-swagger; DO NOT EDIT.

package virtual_machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewTerminateInstanceParams creates a new TerminateInstanceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewTerminateInstanceParams() *TerminateInstanceParams {
	return &TerminateInstanceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewTerminateInstanceParamsWithTimeout creates a new TerminateInstanceParams object
// with the ability to set a timeout on a request.
func NewTerminateInstanceParamsWithTimeout(timeout time.Duration) *TerminateInstanceParams {
	return &TerminateInstanceParams{
		timeout: timeout,
	}
}

// NewTerminateInstanceParamsWithContext creates a new TerminateInstanceParams object
// with the ability to set a context for a request.
func NewTerminateInstanceParamsWithContext(ctx context.Context) *TerminateInstanceParams {
	return &TerminateInstanceParams{
		Context: ctx,
	}
}

// NewTerminateInstanceParamsWithHTTPClient creates a new TerminateInstanceParams object
// with the ability to set a custom HTTPClient for a request.
func NewTerminateInstanceParamsWithHTTPClient(client *http.Client) *TerminateInstanceParams {
	return &TerminateInstanceParams{
		HTTPClient: client,
	}
}

/*
TerminateInstanceParams contains all the parameters to send to the API endpoint

	for the terminate instance operation.

	Typically these are written to a http.Request.
*/
type TerminateInstanceParams struct {

	// InstanceID.
	InstanceID string

	// ProjectID.
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the terminate instance params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TerminateInstanceParams) WithDefaults() *TerminateInstanceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the terminate instance params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TerminateInstanceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the terminate instance params
func (o *TerminateInstanceParams) WithTimeout(timeout time.Duration) *TerminateInstanceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the terminate instance params
func (o *TerminateInstanceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the terminate instance params
func (o *TerminateInstanceParams) WithContext(ctx context.Context) *TerminateInstanceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the terminate instance params
func (o *TerminateInstanceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the terminate instance params
func (o *TerminateInstanceParams) WithHTTPClient(client *http.Client) *TerminateInstanceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the terminate instance params
func (o *TerminateInstanceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInstanceID adds the instanceID to the terminate instance params
func (o *TerminateInstanceParams) WithInstanceID(instanceID string) *TerminateInstanceParams {
	o.SetInstanceID(instanceID)
	return o
}

// SetInstanceID adds the instanceId to the terminate instance params
func (o *TerminateInstanceParams) SetInstanceID(instanceID string) {
	o.InstanceID = instanceID
}

// WithProjectID adds the projectID to the terminate instance params
func (o *TerminateInstanceParams) WithProjectID(projectID string) *TerminateInstanceParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the terminate instance params
func (o *TerminateInstanceParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *TerminateInstanceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param instanceId
	if err := r.SetPathParam("instanceId", o.InstanceID); err != nil {
		return err
	}

	// path param projectId
	if err := r.SetPathParam("projectId", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
