// Code generated by go-swagger; DO NOT EDIT.

package virtual_machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/CudoVentures/terraform-provider-cudo/internal/models"
)

// UpdatePrivateVMImageReader is a Reader for the UpdatePrivateVMImage structure.
type UpdatePrivateVMImageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdatePrivateVMImageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdatePrivateVMImageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewUpdatePrivateVMImageDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUpdatePrivateVMImageOK creates a UpdatePrivateVMImageOK with default headers values
func NewUpdatePrivateVMImageOK() *UpdatePrivateVMImageOK {
	return &UpdatePrivateVMImageOK{}
}

/*
UpdatePrivateVMImageOK describes a response with status code 200, with default header values.

A successful response.
*/
type UpdatePrivateVMImageOK struct {
	Payload models.UpdatePrivateVMImageResponse
}

// IsSuccess returns true when this update private Vm image o k response has a 2xx status code
func (o *UpdatePrivateVMImageOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update private Vm image o k response has a 3xx status code
func (o *UpdatePrivateVMImageOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update private Vm image o k response has a 4xx status code
func (o *UpdatePrivateVMImageOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this update private Vm image o k response has a 5xx status code
func (o *UpdatePrivateVMImageOK) IsServerError() bool {
	return false
}

// IsCode returns true when this update private Vm image o k response a status code equal to that given
func (o *UpdatePrivateVMImageOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the update private Vm image o k response
func (o *UpdatePrivateVMImageOK) Code() int {
	return 200
}

func (o *UpdatePrivateVMImageOK) Error() string {
	return fmt.Sprintf("[POST /v1/projects/{projectId}/images/{id}][%d] updatePrivateVmImageOK  %+v", 200, o.Payload)
}

func (o *UpdatePrivateVMImageOK) String() string {
	return fmt.Sprintf("[POST /v1/projects/{projectId}/images/{id}][%d] updatePrivateVmImageOK  %+v", 200, o.Payload)
}

func (o *UpdatePrivateVMImageOK) GetPayload() models.UpdatePrivateVMImageResponse {
	return o.Payload
}

func (o *UpdatePrivateVMImageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdatePrivateVMImageDefault creates a UpdatePrivateVMImageDefault with default headers values
func NewUpdatePrivateVMImageDefault(code int) *UpdatePrivateVMImageDefault {
	return &UpdatePrivateVMImageDefault{
		_statusCode: code,
	}
}

/*
UpdatePrivateVMImageDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type UpdatePrivateVMImageDefault struct {
	_statusCode int

	Payload *models.Status
}

// IsSuccess returns true when this update private VM image default response has a 2xx status code
func (o *UpdatePrivateVMImageDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this update private VM image default response has a 3xx status code
func (o *UpdatePrivateVMImageDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this update private VM image default response has a 4xx status code
func (o *UpdatePrivateVMImageDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this update private VM image default response has a 5xx status code
func (o *UpdatePrivateVMImageDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this update private VM image default response a status code equal to that given
func (o *UpdatePrivateVMImageDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the update private VM image default response
func (o *UpdatePrivateVMImageDefault) Code() int {
	return o._statusCode
}

func (o *UpdatePrivateVMImageDefault) Error() string {
	return fmt.Sprintf("[POST /v1/projects/{projectId}/images/{id}][%d] UpdatePrivateVMImage default  %+v", o._statusCode, o.Payload)
}

func (o *UpdatePrivateVMImageDefault) String() string {
	return fmt.Sprintf("[POST /v1/projects/{projectId}/images/{id}][%d] UpdatePrivateVMImage default  %+v", o._statusCode, o.Payload)
}

func (o *UpdatePrivateVMImageDefault) GetPayload() *models.Status {
	return o.Payload
}

func (o *UpdatePrivateVMImageDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
