// Code generated by go-swagger; DO NOT EDIT.

package networks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/CudoVentures/terraform-provider-cudo/internal/models"
)

// CreateSecurityGroupReader is a Reader for the CreateSecurityGroup structure.
type CreateSecurityGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateSecurityGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateSecurityGroupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCreateSecurityGroupDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreateSecurityGroupOK creates a CreateSecurityGroupOK with default headers values
func NewCreateSecurityGroupOK() *CreateSecurityGroupOK {
	return &CreateSecurityGroupOK{}
}

/*
CreateSecurityGroupOK describes a response with status code 200, with default header values.

A successful response.
*/
type CreateSecurityGroupOK struct {
	Payload *models.CreateSecurityGroupResponse
}

// IsSuccess returns true when this create security group o k response has a 2xx status code
func (o *CreateSecurityGroupOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create security group o k response has a 3xx status code
func (o *CreateSecurityGroupOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create security group o k response has a 4xx status code
func (o *CreateSecurityGroupOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create security group o k response has a 5xx status code
func (o *CreateSecurityGroupOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create security group o k response a status code equal to that given
func (o *CreateSecurityGroupOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the create security group o k response
func (o *CreateSecurityGroupOK) Code() int {
	return 200
}

func (o *CreateSecurityGroupOK) Error() string {
	return fmt.Sprintf("[POST /v1/projects/{securityGroup.projectId}/networks/security-groups][%d] createSecurityGroupOK  %+v", 200, o.Payload)
}

func (o *CreateSecurityGroupOK) String() string {
	return fmt.Sprintf("[POST /v1/projects/{securityGroup.projectId}/networks/security-groups][%d] createSecurityGroupOK  %+v", 200, o.Payload)
}

func (o *CreateSecurityGroupOK) GetPayload() *models.CreateSecurityGroupResponse {
	return o.Payload
}

func (o *CreateSecurityGroupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreateSecurityGroupResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateSecurityGroupDefault creates a CreateSecurityGroupDefault with default headers values
func NewCreateSecurityGroupDefault(code int) *CreateSecurityGroupDefault {
	return &CreateSecurityGroupDefault{
		_statusCode: code,
	}
}

/*
CreateSecurityGroupDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type CreateSecurityGroupDefault struct {
	_statusCode int

	Payload *models.Status
}

// IsSuccess returns true when this create security group default response has a 2xx status code
func (o *CreateSecurityGroupDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this create security group default response has a 3xx status code
func (o *CreateSecurityGroupDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this create security group default response has a 4xx status code
func (o *CreateSecurityGroupDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this create security group default response has a 5xx status code
func (o *CreateSecurityGroupDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this create security group default response a status code equal to that given
func (o *CreateSecurityGroupDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the create security group default response
func (o *CreateSecurityGroupDefault) Code() int {
	return o._statusCode
}

func (o *CreateSecurityGroupDefault) Error() string {
	return fmt.Sprintf("[POST /v1/projects/{securityGroup.projectId}/networks/security-groups][%d] CreateSecurityGroup default  %+v", o._statusCode, o.Payload)
}

func (o *CreateSecurityGroupDefault) String() string {
	return fmt.Sprintf("[POST /v1/projects/{securityGroup.projectId}/networks/security-groups][%d] CreateSecurityGroup default  %+v", o._statusCode, o.Payload)
}

func (o *CreateSecurityGroupDefault) GetPayload() *models.Status {
	return o.Payload
}

func (o *CreateSecurityGroupDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
CreateSecurityGroupBody create security group body
swagger:model CreateSecurityGroupBody
*/
type CreateSecurityGroupBody struct {

	// data center Id
	// Required: true
	DataCenterID *string `json:"dataCenterId"`

	// description
	Description string `json:"description,omitempty"`

	// id
	// Required: true
	ID *string `json:"id"`

	// rules
	Rules []*models.Rule `json:"rules"`
}

// Validate validates this create security group body
func (o *CreateSecurityGroupBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDataCenterID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateRules(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreateSecurityGroupBody) validateDataCenterID(formats strfmt.Registry) error {

	if err := validate.Required("securityGroup"+"."+"dataCenterId", "body", o.DataCenterID); err != nil {
		return err
	}

	return nil
}

func (o *CreateSecurityGroupBody) validateID(formats strfmt.Registry) error {

	if err := validate.Required("securityGroup"+"."+"id", "body", o.ID); err != nil {
		return err
	}

	return nil
}

func (o *CreateSecurityGroupBody) validateRules(formats strfmt.Registry) error {
	if swag.IsZero(o.Rules) { // not required
		return nil
	}

	for i := 0; i < len(o.Rules); i++ {
		if swag.IsZero(o.Rules[i]) { // not required
			continue
		}

		if o.Rules[i] != nil {
			if err := o.Rules[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("securityGroup" + "." + "rules" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("securityGroup" + "." + "rules" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this create security group body based on the context it is used
func (o *CreateSecurityGroupBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateRules(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreateSecurityGroupBody) contextValidateRules(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Rules); i++ {

		if o.Rules[i] != nil {
			if err := o.Rules[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("securityGroup" + "." + "rules" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("securityGroup" + "." + "rules" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *CreateSecurityGroupBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateSecurityGroupBody) UnmarshalBinary(b []byte) error {
	var res CreateSecurityGroupBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
