// Code generated by go-swagger; DO NOT EDIT.

package networks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/CudoVentures/terraform-provider-cudo/internal/models"
)

// DeleteSecurityGroupReader is a Reader for the DeleteSecurityGroup structure.
type DeleteSecurityGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteSecurityGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteSecurityGroupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDeleteSecurityGroupDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteSecurityGroupOK creates a DeleteSecurityGroupOK with default headers values
func NewDeleteSecurityGroupOK() *DeleteSecurityGroupOK {
	return &DeleteSecurityGroupOK{}
}

/*
DeleteSecurityGroupOK describes a response with status code 200, with default header values.

A successful response.
*/
type DeleteSecurityGroupOK struct {
	Payload models.DeleteSecurityGroupResponse
}

// IsSuccess returns true when this delete security group o k response has a 2xx status code
func (o *DeleteSecurityGroupOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete security group o k response has a 3xx status code
func (o *DeleteSecurityGroupOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete security group o k response has a 4xx status code
func (o *DeleteSecurityGroupOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete security group o k response has a 5xx status code
func (o *DeleteSecurityGroupOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete security group o k response a status code equal to that given
func (o *DeleteSecurityGroupOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete security group o k response
func (o *DeleteSecurityGroupOK) Code() int {
	return 200
}

func (o *DeleteSecurityGroupOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/projects/{projectId}/networks/security-groups/{id}][%d] deleteSecurityGroupOK  %+v", 200, o.Payload)
}

func (o *DeleteSecurityGroupOK) String() string {
	return fmt.Sprintf("[DELETE /v1/projects/{projectId}/networks/security-groups/{id}][%d] deleteSecurityGroupOK  %+v", 200, o.Payload)
}

func (o *DeleteSecurityGroupOK) GetPayload() models.DeleteSecurityGroupResponse {
	return o.Payload
}

func (o *DeleteSecurityGroupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteSecurityGroupDefault creates a DeleteSecurityGroupDefault with default headers values
func NewDeleteSecurityGroupDefault(code int) *DeleteSecurityGroupDefault {
	return &DeleteSecurityGroupDefault{
		_statusCode: code,
	}
}

/*
DeleteSecurityGroupDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type DeleteSecurityGroupDefault struct {
	_statusCode int

	Payload *models.Status
}

// IsSuccess returns true when this delete security group default response has a 2xx status code
func (o *DeleteSecurityGroupDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this delete security group default response has a 3xx status code
func (o *DeleteSecurityGroupDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this delete security group default response has a 4xx status code
func (o *DeleteSecurityGroupDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this delete security group default response has a 5xx status code
func (o *DeleteSecurityGroupDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this delete security group default response a status code equal to that given
func (o *DeleteSecurityGroupDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the delete security group default response
func (o *DeleteSecurityGroupDefault) Code() int {
	return o._statusCode
}

func (o *DeleteSecurityGroupDefault) Error() string {
	return fmt.Sprintf("[DELETE /v1/projects/{projectId}/networks/security-groups/{id}][%d] DeleteSecurityGroup default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteSecurityGroupDefault) String() string {
	return fmt.Sprintf("[DELETE /v1/projects/{projectId}/networks/security-groups/{id}][%d] DeleteSecurityGroup default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteSecurityGroupDefault) GetPayload() *models.Status {
	return o.Payload
}

func (o *DeleteSecurityGroupDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
