// Code generated by go-swagger; DO NOT EDIT.

package networks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewStopNetworkParams creates a new StopNetworkParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewStopNetworkParams() *StopNetworkParams {
	return &StopNetworkParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewStopNetworkParamsWithTimeout creates a new StopNetworkParams object
// with the ability to set a timeout on a request.
func NewStopNetworkParamsWithTimeout(timeout time.Duration) *StopNetworkParams {
	return &StopNetworkParams{
		timeout: timeout,
	}
}

// NewStopNetworkParamsWithContext creates a new StopNetworkParams object
// with the ability to set a context for a request.
func NewStopNetworkParamsWithContext(ctx context.Context) *StopNetworkParams {
	return &StopNetworkParams{
		Context: ctx,
	}
}

// NewStopNetworkParamsWithHTTPClient creates a new StopNetworkParams object
// with the ability to set a custom HTTPClient for a request.
func NewStopNetworkParamsWithHTTPClient(client *http.Client) *StopNetworkParams {
	return &StopNetworkParams{
		HTTPClient: client,
	}
}

/*
StopNetworkParams contains all the parameters to send to the API endpoint

	for the stop network operation.

	Typically these are written to a http.Request.
*/
type StopNetworkParams struct {

	// NetworkID.
	NetworkID string

	// ProjectID.
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the stop network params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StopNetworkParams) WithDefaults() *StopNetworkParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the stop network params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StopNetworkParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the stop network params
func (o *StopNetworkParams) WithTimeout(timeout time.Duration) *StopNetworkParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the stop network params
func (o *StopNetworkParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the stop network params
func (o *StopNetworkParams) WithContext(ctx context.Context) *StopNetworkParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the stop network params
func (o *StopNetworkParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the stop network params
func (o *StopNetworkParams) WithHTTPClient(client *http.Client) *StopNetworkParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the stop network params
func (o *StopNetworkParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNetworkID adds the networkID to the stop network params
func (o *StopNetworkParams) WithNetworkID(networkID string) *StopNetworkParams {
	o.SetNetworkID(networkID)
	return o
}

// SetNetworkID adds the networkId to the stop network params
func (o *StopNetworkParams) SetNetworkID(networkID string) {
	o.NetworkID = networkID
}

// WithProjectID adds the projectID to the stop network params
func (o *StopNetworkParams) WithProjectID(projectID string) *StopNetworkParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the stop network params
func (o *StopNetworkParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *StopNetworkParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param networkId
	if err := r.SetPathParam("networkId", o.NetworkID); err != nil {
		return err
	}

	// path param projectId
	if err := r.SetPathParam("projectId", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
