// Code generated by go-swagger; DO NOT EDIT.

package search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/CudoVentures/terraform-provider-cudo/internal/models"
)

// ListOSImagesReader is a Reader for the ListOSImages structure.
type ListOSImagesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListOSImagesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListOSImagesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListOSImagesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListOSImagesOK creates a ListOSImagesOK with default headers values
func NewListOSImagesOK() *ListOSImagesOK {
	return &ListOSImagesOK{}
}

/*
	ListOSImagesOK describes a response with status code 200, with default header values.

A successful response.
*/
type ListOSImagesOK struct {
	Payload *models.ListOSImagesResponse
}

// IsSuccess returns true when this list o s images o k response has a 2xx status code
func (o *ListOSImagesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list o s images o k response has a 3xx status code
func (o *ListOSImagesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list o s images o k response has a 4xx status code
func (o *ListOSImagesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list o s images o k response has a 5xx status code
func (o *ListOSImagesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list o s images o k response a status code equal to that given
func (o *ListOSImagesOK) IsCode(code int) bool {
	return code == 200
}

func (o *ListOSImagesOK) Error() string {
	return fmt.Sprintf("[GET /v1/compute/images][%d] listOSImagesOK  %+v", 200, o.Payload)
}

func (o *ListOSImagesOK) String() string {
	return fmt.Sprintf("[GET /v1/compute/images][%d] listOSImagesOK  %+v", 200, o.Payload)
}

func (o *ListOSImagesOK) GetPayload() *models.ListOSImagesResponse {
	return o.Payload
}

func (o *ListOSImagesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ListOSImagesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListOSImagesDefault creates a ListOSImagesDefault with default headers values
func NewListOSImagesDefault(code int) *ListOSImagesDefault {
	return &ListOSImagesDefault{
		_statusCode: code,
	}
}

/*
	ListOSImagesDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ListOSImagesDefault struct {
	_statusCode int

	Payload *models.Status
}

// Code gets the status code for the list o s images default response
func (o *ListOSImagesDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this list o s images default response has a 2xx status code
func (o *ListOSImagesDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this list o s images default response has a 3xx status code
func (o *ListOSImagesDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this list o s images default response has a 4xx status code
func (o *ListOSImagesDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this list o s images default response has a 5xx status code
func (o *ListOSImagesDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this list o s images default response a status code equal to that given
func (o *ListOSImagesDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *ListOSImagesDefault) Error() string {
	return fmt.Sprintf("[GET /v1/compute/images][%d] ListOSImages default  %+v", o._statusCode, o.Payload)
}

func (o *ListOSImagesDefault) String() string {
	return fmt.Sprintf("[GET /v1/compute/images][%d] ListOSImages default  %+v", o._statusCode, o.Payload)
}

func (o *ListOSImagesDefault) GetPayload() *models.Status {
	return o.Payload
}

func (o *ListOSImagesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
