// Code generated by go-swagger; DO NOT EDIT.

package search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/CudoVentures/terraform-provider-cudo/internal/models"
)

// SearchDataCentersReader is a Reader for the SearchDataCenters structure.
type SearchDataCentersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SearchDataCentersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSearchDataCentersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewSearchDataCentersDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSearchDataCentersOK creates a SearchDataCentersOK with default headers values
func NewSearchDataCentersOK() *SearchDataCentersOK {
	return &SearchDataCentersOK{}
}

/*
	SearchDataCentersOK describes a response with status code 200, with default header values.

A successful response.
*/
type SearchDataCentersOK struct {
	Payload *models.SearchDataCentersResponse
}

// IsSuccess returns true when this search data centers o k response has a 2xx status code
func (o *SearchDataCentersOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this search data centers o k response has a 3xx status code
func (o *SearchDataCentersOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this search data centers o k response has a 4xx status code
func (o *SearchDataCentersOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this search data centers o k response has a 5xx status code
func (o *SearchDataCentersOK) IsServerError() bool {
	return false
}

// IsCode returns true when this search data centers o k response a status code equal to that given
func (o *SearchDataCentersOK) IsCode(code int) bool {
	return code == 200
}

func (o *SearchDataCentersOK) Error() string {
	return fmt.Sprintf("[GET /v1/compute/data-centers][%d] searchDataCentersOK  %+v", 200, o.Payload)
}

func (o *SearchDataCentersOK) String() string {
	return fmt.Sprintf("[GET /v1/compute/data-centers][%d] searchDataCentersOK  %+v", 200, o.Payload)
}

func (o *SearchDataCentersOK) GetPayload() *models.SearchDataCentersResponse {
	return o.Payload
}

func (o *SearchDataCentersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SearchDataCentersResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSearchDataCentersDefault creates a SearchDataCentersDefault with default headers values
func NewSearchDataCentersDefault(code int) *SearchDataCentersDefault {
	return &SearchDataCentersDefault{
		_statusCode: code,
	}
}

/*
	SearchDataCentersDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type SearchDataCentersDefault struct {
	_statusCode int

	Payload *models.Status
}

// Code gets the status code for the search data centers default response
func (o *SearchDataCentersDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this search data centers default response has a 2xx status code
func (o *SearchDataCentersDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this search data centers default response has a 3xx status code
func (o *SearchDataCentersDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this search data centers default response has a 4xx status code
func (o *SearchDataCentersDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this search data centers default response has a 5xx status code
func (o *SearchDataCentersDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this search data centers default response a status code equal to that given
func (o *SearchDataCentersDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *SearchDataCentersDefault) Error() string {
	return fmt.Sprintf("[GET /v1/compute/data-centers][%d] SearchDataCenters default  %+v", o._statusCode, o.Payload)
}

func (o *SearchDataCentersDefault) String() string {
	return fmt.Sprintf("[GET /v1/compute/data-centers][%d] SearchDataCenters default  %+v", o._statusCode, o.Payload)
}

func (o *SearchDataCentersDefault) GetPayload() *models.Status {
	return o.Payload
}

func (o *SearchDataCentersDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
