// Code generated by go-swagger; DO NOT EDIT.

package search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/CudoVentures/terraform-provider-cudo/internal/models"
)

// SearchComputeReader is a Reader for the SearchCompute structure.
type SearchComputeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SearchComputeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSearchComputeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewSearchComputeDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSearchComputeOK creates a SearchComputeOK with default headers values
func NewSearchComputeOK() *SearchComputeOK {
	return &SearchComputeOK{}
}

/*
	SearchComputeOK describes a response with status code 200, with default header values.

A successful response.
*/
type SearchComputeOK struct {
	Payload *models.SearchComputeResponse
}

// IsSuccess returns true when this search compute o k response has a 2xx status code
func (o *SearchComputeOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this search compute o k response has a 3xx status code
func (o *SearchComputeOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this search compute o k response has a 4xx status code
func (o *SearchComputeOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this search compute o k response has a 5xx status code
func (o *SearchComputeOK) IsServerError() bool {
	return false
}

// IsCode returns true when this search compute o k response a status code equal to that given
func (o *SearchComputeOK) IsCode(code int) bool {
	return code == 200
}

func (o *SearchComputeOK) Error() string {
	return fmt.Sprintf("[GET /v1/compute/search][%d] searchComputeOK  %+v", 200, o.Payload)
}

func (o *SearchComputeOK) String() string {
	return fmt.Sprintf("[GET /v1/compute/search][%d] searchComputeOK  %+v", 200, o.Payload)
}

func (o *SearchComputeOK) GetPayload() *models.SearchComputeResponse {
	return o.Payload
}

func (o *SearchComputeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SearchComputeResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSearchComputeDefault creates a SearchComputeDefault with default headers values
func NewSearchComputeDefault(code int) *SearchComputeDefault {
	return &SearchComputeDefault{
		_statusCode: code,
	}
}

/*
	SearchComputeDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type SearchComputeDefault struct {
	_statusCode int

	Payload *models.Status
}

// Code gets the status code for the search compute default response
func (o *SearchComputeDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this search compute default response has a 2xx status code
func (o *SearchComputeDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this search compute default response has a 3xx status code
func (o *SearchComputeDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this search compute default response has a 4xx status code
func (o *SearchComputeDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this search compute default response has a 5xx status code
func (o *SearchComputeDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this search compute default response a status code equal to that given
func (o *SearchComputeDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *SearchComputeDefault) Error() string {
	return fmt.Sprintf("[GET /v1/compute/search][%d] SearchCompute default  %+v", o._statusCode, o.Payload)
}

func (o *SearchComputeDefault) String() string {
	return fmt.Sprintf("[GET /v1/compute/search][%d] SearchCompute default  %+v", o._statusCode, o.Payload)
}

func (o *SearchComputeDefault) GetPayload() *models.Status {
	return o.Payload
}

func (o *SearchComputeDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
