// Code generated by go-swagger; DO NOT EDIT.

package api_keys

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/CudoVentures/terraform-provider-cudo/internal/models"
)

// GenerateAPIKeyReader is a Reader for the GenerateAPIKey structure.
type GenerateAPIKeyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GenerateAPIKeyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGenerateAPIKeyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGenerateAPIKeyDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGenerateAPIKeyOK creates a GenerateAPIKeyOK with default headers values
func NewGenerateAPIKeyOK() *GenerateAPIKeyOK {
	return &GenerateAPIKeyOK{}
}

/*
GenerateAPIKeyOK describes a response with status code 200, with default header values.

A successful response.
*/
type GenerateAPIKeyOK struct {
	Payload *models.APIKey
}

// IsSuccess returns true when this generate Api key o k response has a 2xx status code
func (o *GenerateAPIKeyOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this generate Api key o k response has a 3xx status code
func (o *GenerateAPIKeyOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this generate Api key o k response has a 4xx status code
func (o *GenerateAPIKeyOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this generate Api key o k response has a 5xx status code
func (o *GenerateAPIKeyOK) IsServerError() bool {
	return false
}

// IsCode returns true when this generate Api key o k response a status code equal to that given
func (o *GenerateAPIKeyOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the generate Api key o k response
func (o *GenerateAPIKeyOK) Code() int {
	return 200
}

func (o *GenerateAPIKeyOK) Error() string {
	return fmt.Sprintf("[POST /v1/api-keys][%d] generateApiKeyOK  %+v", 200, o.Payload)
}

func (o *GenerateAPIKeyOK) String() string {
	return fmt.Sprintf("[POST /v1/api-keys][%d] generateApiKeyOK  %+v", 200, o.Payload)
}

func (o *GenerateAPIKeyOK) GetPayload() *models.APIKey {
	return o.Payload
}

func (o *GenerateAPIKeyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIKey)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGenerateAPIKeyDefault creates a GenerateAPIKeyDefault with default headers values
func NewGenerateAPIKeyDefault(code int) *GenerateAPIKeyDefault {
	return &GenerateAPIKeyDefault{
		_statusCode: code,
	}
}

/*
GenerateAPIKeyDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type GenerateAPIKeyDefault struct {
	_statusCode int

	Payload *models.Status
}

// IsSuccess returns true when this generate Api key default response has a 2xx status code
func (o *GenerateAPIKeyDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this generate Api key default response has a 3xx status code
func (o *GenerateAPIKeyDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this generate Api key default response has a 4xx status code
func (o *GenerateAPIKeyDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this generate Api key default response has a 5xx status code
func (o *GenerateAPIKeyDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this generate Api key default response a status code equal to that given
func (o *GenerateAPIKeyDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the generate Api key default response
func (o *GenerateAPIKeyDefault) Code() int {
	return o._statusCode
}

func (o *GenerateAPIKeyDefault) Error() string {
	return fmt.Sprintf("[POST /v1/api-keys][%d] GenerateApiKey default  %+v", o._statusCode, o.Payload)
}

func (o *GenerateAPIKeyDefault) String() string {
	return fmt.Sprintf("[POST /v1/api-keys][%d] GenerateApiKey default  %+v", o._statusCode, o.Payload)
}

func (o *GenerateAPIKeyDefault) GetPayload() *models.Status {
	return o.Payload
}

func (o *GenerateAPIKeyDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
