// Code generated by go-swagger; DO NOT EDIT.

package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"cudo.org/v1/terraform-provider-cudo/internal/models"
)

// GetProjectCurrentSpendReader is a Reader for the GetProjectCurrentSpend structure.
type GetProjectCurrentSpendReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProjectCurrentSpendReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetProjectCurrentSpendOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetProjectCurrentSpendDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetProjectCurrentSpendOK creates a GetProjectCurrentSpendOK with default headers values
func NewGetProjectCurrentSpendOK() *GetProjectCurrentSpendOK {
	return &GetProjectCurrentSpendOK{}
}

/*
	GetProjectCurrentSpendOK describes a response with status code 200, with default header values.

A successful response.
*/
type GetProjectCurrentSpendOK struct {
	Payload *models.ProjectSpend
}

// IsSuccess returns true when this get project current spend o k response has a 2xx status code
func (o *GetProjectCurrentSpendOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get project current spend o k response has a 3xx status code
func (o *GetProjectCurrentSpendOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get project current spend o k response has a 4xx status code
func (o *GetProjectCurrentSpendOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get project current spend o k response has a 5xx status code
func (o *GetProjectCurrentSpendOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get project current spend o k response a status code equal to that given
func (o *GetProjectCurrentSpendOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetProjectCurrentSpendOK) Error() string {
	return fmt.Sprintf("[GET /v1/projects/{id}/spend/current][%d] getProjectCurrentSpendOK  %+v", 200, o.Payload)
}

func (o *GetProjectCurrentSpendOK) String() string {
	return fmt.Sprintf("[GET /v1/projects/{id}/spend/current][%d] getProjectCurrentSpendOK  %+v", 200, o.Payload)
}

func (o *GetProjectCurrentSpendOK) GetPayload() *models.ProjectSpend {
	return o.Payload
}

func (o *GetProjectCurrentSpendOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProjectSpend)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProjectCurrentSpendDefault creates a GetProjectCurrentSpendDefault with default headers values
func NewGetProjectCurrentSpendDefault(code int) *GetProjectCurrentSpendDefault {
	return &GetProjectCurrentSpendDefault{
		_statusCode: code,
	}
}

/*
	GetProjectCurrentSpendDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type GetProjectCurrentSpendDefault struct {
	_statusCode int

	Payload *models.Status
}

// Code gets the status code for the get project current spend default response
func (o *GetProjectCurrentSpendDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this get project current spend default response has a 2xx status code
func (o *GetProjectCurrentSpendDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get project current spend default response has a 3xx status code
func (o *GetProjectCurrentSpendDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get project current spend default response has a 4xx status code
func (o *GetProjectCurrentSpendDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get project current spend default response has a 5xx status code
func (o *GetProjectCurrentSpendDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get project current spend default response a status code equal to that given
func (o *GetProjectCurrentSpendDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *GetProjectCurrentSpendDefault) Error() string {
	return fmt.Sprintf("[GET /v1/projects/{id}/spend/current][%d] GetProjectCurrentSpend default  %+v", o._statusCode, o.Payload)
}

func (o *GetProjectCurrentSpendDefault) String() string {
	return fmt.Sprintf("[GET /v1/projects/{id}/spend/current][%d] GetProjectCurrentSpend default  %+v", o._statusCode, o.Payload)
}

func (o *GetProjectCurrentSpendDefault) GetPayload() *models.Status {
	return o.Payload
}

func (o *GetProjectCurrentSpendDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
