// Code generated by go-swagger; DO NOT EDIT.

package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/CudoVentures/terraform-provider-cudo/internal/models"
)

// GetProjectSpendHistoryReader is a Reader for the GetProjectSpendHistory structure.
type GetProjectSpendHistoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProjectSpendHistoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetProjectSpendHistoryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetProjectSpendHistoryDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetProjectSpendHistoryOK creates a GetProjectSpendHistoryOK with default headers values
func NewGetProjectSpendHistoryOK() *GetProjectSpendHistoryOK {
	return &GetProjectSpendHistoryOK{}
}

/*
GetProjectSpendHistoryOK describes a response with status code 200, with default header values.

A successful response.
*/
type GetProjectSpendHistoryOK struct {
	Payload *models.GetProjectSpendHistoryResponse
}

// IsSuccess returns true when this get project spend history o k response has a 2xx status code
func (o *GetProjectSpendHistoryOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get project spend history o k response has a 3xx status code
func (o *GetProjectSpendHistoryOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get project spend history o k response has a 4xx status code
func (o *GetProjectSpendHistoryOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get project spend history o k response has a 5xx status code
func (o *GetProjectSpendHistoryOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get project spend history o k response a status code equal to that given
func (o *GetProjectSpendHistoryOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get project spend history o k response
func (o *GetProjectSpendHistoryOK) Code() int {
	return 200
}

func (o *GetProjectSpendHistoryOK) Error() string {
	return fmt.Sprintf("[GET /v1/projects/{id}/spend][%d] getProjectSpendHistoryOK  %+v", 200, o.Payload)
}

func (o *GetProjectSpendHistoryOK) String() string {
	return fmt.Sprintf("[GET /v1/projects/{id}/spend][%d] getProjectSpendHistoryOK  %+v", 200, o.Payload)
}

func (o *GetProjectSpendHistoryOK) GetPayload() *models.GetProjectSpendHistoryResponse {
	return o.Payload
}

func (o *GetProjectSpendHistoryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetProjectSpendHistoryResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProjectSpendHistoryDefault creates a GetProjectSpendHistoryDefault with default headers values
func NewGetProjectSpendHistoryDefault(code int) *GetProjectSpendHistoryDefault {
	return &GetProjectSpendHistoryDefault{
		_statusCode: code,
	}
}

/*
GetProjectSpendHistoryDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type GetProjectSpendHistoryDefault struct {
	_statusCode int

	Payload *models.Status
}

// IsSuccess returns true when this get project spend history default response has a 2xx status code
func (o *GetProjectSpendHistoryDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get project spend history default response has a 3xx status code
func (o *GetProjectSpendHistoryDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get project spend history default response has a 4xx status code
func (o *GetProjectSpendHistoryDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get project spend history default response has a 5xx status code
func (o *GetProjectSpendHistoryDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get project spend history default response a status code equal to that given
func (o *GetProjectSpendHistoryDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get project spend history default response
func (o *GetProjectSpendHistoryDefault) Code() int {
	return o._statusCode
}

func (o *GetProjectSpendHistoryDefault) Error() string {
	return fmt.Sprintf("[GET /v1/projects/{id}/spend][%d] GetProjectSpendHistory default  %+v", o._statusCode, o.Payload)
}

func (o *GetProjectSpendHistoryDefault) String() string {
	return fmt.Sprintf("[GET /v1/projects/{id}/spend][%d] GetProjectSpendHistory default  %+v", o._statusCode, o.Payload)
}

func (o *GetProjectSpendHistoryDefault) GetPayload() *models.Status {
	return o.Payload
}

func (o *GetProjectSpendHistoryDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
