// Code generated by go-swagger; DO NOT EDIT.

package ssh_keys

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/CudoVentures/terraform-provider-cudo/internal/models"
)

// DeleteSSHKeyReader is a Reader for the DeleteSSHKey structure.
type DeleteSSHKeyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteSSHKeyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteSSHKeyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDeleteSSHKeyDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteSSHKeyOK creates a DeleteSSHKeyOK with default headers values
func NewDeleteSSHKeyOK() *DeleteSSHKeyOK {
	return &DeleteSSHKeyOK{}
}

/*
DeleteSSHKeyOK describes a response with status code 200, with default header values.

A successful response.
*/
type DeleteSSHKeyOK struct {
	Payload interface{}
}

// IsSuccess returns true when this delete Ssh key o k response has a 2xx status code
func (o *DeleteSSHKeyOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete Ssh key o k response has a 3xx status code
func (o *DeleteSSHKeyOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete Ssh key o k response has a 4xx status code
func (o *DeleteSSHKeyOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete Ssh key o k response has a 5xx status code
func (o *DeleteSSHKeyOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete Ssh key o k response a status code equal to that given
func (o *DeleteSSHKeyOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete Ssh key o k response
func (o *DeleteSSHKeyOK) Code() int {
	return 200
}

func (o *DeleteSSHKeyOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/ssh-keys/{id}][%d] deleteSshKeyOK  %+v", 200, o.Payload)
}

func (o *DeleteSSHKeyOK) String() string {
	return fmt.Sprintf("[DELETE /v1/ssh-keys/{id}][%d] deleteSshKeyOK  %+v", 200, o.Payload)
}

func (o *DeleteSSHKeyOK) GetPayload() interface{} {
	return o.Payload
}

func (o *DeleteSSHKeyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteSSHKeyDefault creates a DeleteSSHKeyDefault with default headers values
func NewDeleteSSHKeyDefault(code int) *DeleteSSHKeyDefault {
	return &DeleteSSHKeyDefault{
		_statusCode: code,
	}
}

/*
DeleteSSHKeyDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type DeleteSSHKeyDefault struct {
	_statusCode int

	Payload *models.Status
}

// IsSuccess returns true when this delete Ssh key default response has a 2xx status code
func (o *DeleteSSHKeyDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this delete Ssh key default response has a 3xx status code
func (o *DeleteSSHKeyDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this delete Ssh key default response has a 4xx status code
func (o *DeleteSSHKeyDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this delete Ssh key default response has a 5xx status code
func (o *DeleteSSHKeyDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this delete Ssh key default response a status code equal to that given
func (o *DeleteSSHKeyDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the delete Ssh key default response
func (o *DeleteSSHKeyDefault) Code() int {
	return o._statusCode
}

func (o *DeleteSSHKeyDefault) Error() string {
	return fmt.Sprintf("[DELETE /v1/ssh-keys/{id}][%d] DeleteSshKey default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteSSHKeyDefault) String() string {
	return fmt.Sprintf("[DELETE /v1/ssh-keys/{id}][%d] DeleteSshKey default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteSSHKeyDefault) GetPayload() *models.Status {
	return o.Payload
}

func (o *DeleteSSHKeyDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
