// Code generated by go-swagger; DO NOT EDIT.

package ssh_keys

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/CudoVentures/terraform-provider-cudo/internal/models"
)

// GetSSHKeyReader is a Reader for the GetSSHKey structure.
type GetSSHKeyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSSHKeyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSSHKeyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetSSHKeyDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetSSHKeyOK creates a GetSSHKeyOK with default headers values
func NewGetSSHKeyOK() *GetSSHKeyOK {
	return &GetSSHKeyOK{}
}

/*
GetSSHKeyOK describes a response with status code 200, with default header values.

A successful response.
*/
type GetSSHKeyOK struct {
	Payload *models.SSHKey
}

// IsSuccess returns true when this get Ssh key o k response has a 2xx status code
func (o *GetSSHKeyOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Ssh key o k response has a 3xx status code
func (o *GetSSHKeyOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Ssh key o k response has a 4xx status code
func (o *GetSSHKeyOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Ssh key o k response has a 5xx status code
func (o *GetSSHKeyOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Ssh key o k response a status code equal to that given
func (o *GetSSHKeyOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Ssh key o k response
func (o *GetSSHKeyOK) Code() int {
	return 200
}

func (o *GetSSHKeyOK) Error() string {
	return fmt.Sprintf("[GET /v1/ssh-keys/{id}][%d] getSshKeyOK  %+v", 200, o.Payload)
}

func (o *GetSSHKeyOK) String() string {
	return fmt.Sprintf("[GET /v1/ssh-keys/{id}][%d] getSshKeyOK  %+v", 200, o.Payload)
}

func (o *GetSSHKeyOK) GetPayload() *models.SSHKey {
	return o.Payload
}

func (o *GetSSHKeyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SSHKey)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSSHKeyDefault creates a GetSSHKeyDefault with default headers values
func NewGetSSHKeyDefault(code int) *GetSSHKeyDefault {
	return &GetSSHKeyDefault{
		_statusCode: code,
	}
}

/*
GetSSHKeyDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type GetSSHKeyDefault struct {
	_statusCode int

	Payload *models.Status
}

// IsSuccess returns true when this get Ssh key default response has a 2xx status code
func (o *GetSSHKeyDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get Ssh key default response has a 3xx status code
func (o *GetSSHKeyDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get Ssh key default response has a 4xx status code
func (o *GetSSHKeyDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get Ssh key default response has a 5xx status code
func (o *GetSSHKeyDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get Ssh key default response a status code equal to that given
func (o *GetSSHKeyDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get Ssh key default response
func (o *GetSSHKeyDefault) Code() int {
	return o._statusCode
}

func (o *GetSSHKeyDefault) Error() string {
	return fmt.Sprintf("[GET /v1/ssh-keys/{id}][%d] GetSshKey default  %+v", o._statusCode, o.Payload)
}

func (o *GetSSHKeyDefault) String() string {
	return fmt.Sprintf("[GET /v1/ssh-keys/{id}][%d] GetSshKey default  %+v", o._statusCode, o.Payload)
}

func (o *GetSSHKeyDefault) GetPayload() *models.Status {
	return o.Payload
}

func (o *GetSSHKeyDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
